import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'search.placeholder': 'Search documentation...',
    'search.short': 'Search...',
    
    // Navigation
    'nav.overview': 'Overview',
    'nav.requirements': 'Requirements Analysis',
    'nav.features': 'Core Features',
    'nav.architecture': 'Architecture',
    'nav.userScenarios': 'User Scenarios',
    'nav.roadmap': 'Roadmap',
    'nav.appendix': 'Appendix',
    
    // Sub-nav
    'nav.userPersonas': 'User Personas',
    'nav.painPoints': 'Pain Points',
    'nav.marketResearch': 'Market Research',
    'nav.dataListening': 'Data Listening',
    'nav.aiAnalysis': 'AI Analysis Engine',
    'nav.filtering': 'Filtering & Subscription',
    'nav.approval': 'Approval Workflow',
    'nav.notification': 'Smart Notification',
    'nav.dashboard': 'Dashboard & Analytics',
    'nav.reporting': 'Auto Reporting',
    'nav.comparison': 'Repo Comparison',
    'nav.systemDesign': 'System Design',
    'nav.techStack': 'Tech Stack',
    'nav.dataFlow': 'Data Flow',
    'nav.personalMode': 'Personal Mode',
    'nav.teamMode': 'Team Mode',
    'nav.managerMode': 'Manager Mode',
    'nav.glossary': 'Glossary',
    'nav.references': 'References',
    
    // Overview
    'overview.title': 'Repo-Pulse Documentation',
    'overview.subtitle': 'AI-Powered R&D Efficiency Platform — Transforming scattered repository information into structured, understandable, and actionable insights.',
    'overview.whatIs.title': 'What is Repo-Pulse?',
    'overview.whatIs.description1': 'Repo-Pulse is an AI-driven SaaS platform designed for software development teams. It listens to Git repository activities (Issues, Pull Requests, Commits), performs semantic analysis and risk assessment on the information, and presents it through visualization and intelligent notifications — helping developers and teams efficiently track project progress.',
    'overview.whatIs.description2': 'Unlike traditional code review tools, Repo-Pulse doesn\'t just analyze code quality. It transforms fragmented, redundant code information into structured, understandable, and decision-ready data, enabling teams to move from "reading code updates" to "understanding key information and making decisions."',
    'overview.value.title': 'Core Value Proposition',
    'overview.value.reduce': 'Reduce Information Overload',
    'overview.value.reduce.desc': 'AI automatically filters noise and highlights critical changes, reducing information processing costs by 70%.',
    'overview.value.intelligent': 'Intelligent Understanding',
    'overview.value.intelligent.desc': 'Semantic analysis of code changes, not just keyword matching. Understand the business meaning behind modifications.',
    'overview.value.risk': 'Risk Prevention',
    'overview.value.risk.desc': 'Automatically identify high-risk changes, security vulnerabilities, and potential issues before they reach production.',
    'overview.features.title': 'Key Features Overview',
    'overview.quickStart.title': 'Quick Start',
    'overview.quickStart.step1': 'Connect your GitHub or GitLab repositories',
    'overview.quickStart.step2': 'Configure AI analysis preferences and notification rules',
    'overview.quickStart.step3': 'Start receiving intelligent summaries and insights',
    'overview.users.title': 'Who is it for?',
    'overview.users.individual': 'Individual Developers',
    'overview.users.individual.desc': 'Track multiple open-source projects efficiently without being overwhelmed by notifications',
    'overview.users.team': 'Development Teams',
    'overview.users.team.desc': 'Improve code review efficiency and reduce risk with AI-assisted analysis',
    'overview.users.manager': 'Engineering Managers',
    'overview.users.manager.desc': 'Data-driven insights into team productivity, code quality trends, and project health',
    
    // Features
    'features.title': 'Core Features',
    'features.subtitle': 'Comprehensive feature set for intelligent R&D efficiency management',
    'features.overview.title': 'Features Overview',
    'features.checklist.title': 'Complete Feature Checklist',
    'features.checklist.subtitle': 'Detailed feature list for development reference',
    
    // Requirements
    'requirements.title': 'Requirements Analysis',
    'requirements.subtitle': 'Understanding user needs, pain points, and market landscape',
    'requirements.personas.title': 'User Personas',
    'requirements.painPoints.title': 'Pain Points Analysis',
    'requirements.market.title': 'Market Research',
    
    // Architecture
    'architecture.title': 'Architecture',
    'architecture.subtitle': 'System design, technology choices, and data flow',
    
    // User Scenarios
    'scenarios.title': 'User Scenarios',
    'scenarios.subtitle': 'How different users interact with Repo-Pulse',
    
    // Roadmap
    'roadmap.title': 'Roadmap',
    'roadmap.subtitle': 'Development timeline and future plans',
    
    // Appendix
    'appendix.title': 'Appendix',
    'appendix.subtitle': 'Additional resources and reference materials',
    
    // Common
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.viewDetails': 'View Details',
    'common.comingSoon': 'Coming Soon',
    'common.inProgress': 'In Progress',
    'common.completed': 'Completed',
    'common.planned': 'Planned',

    // App shell
    'app.layout.title': 'Workspace',
    'app.layout.subtitle': 'AI repository monitor',
    'app.layout.description': 'Track repositories, events, and AI insights',
    'app.layout.menu': 'Open menu',
    'app.layout.notifications': 'Notifications',
    'app.layout.github': 'GitHub',
    'app.layout.docs': 'Docs',
    'app.layout.support': 'Support',
    'app.search.placeholder': 'search repositories, issues, PRs...',
    'app.language.switch': 'Switch language',
    'app.language.english': 'English',
    'app.language.chinese': 'Chinese',
    'app.user.unknown': 'Unknown user',
    'app.user.noEmail': 'No email',

    // App navigation
    'app.nav.dashboard': 'Dashboard',
    'app.nav.repositories': 'Repositories',
    'app.nav.analysis': 'AI Analysis',
    'app.nav.approvals': 'Approvals',
    'app.nav.notifications': 'Notifications',
    'app.nav.reports': 'Reports',
    'app.nav.settings': 'Settings',

    // Auth
    'auth.login.title': 'Sign in to Repo-Pulse',
    'auth.login.description': 'Sign in with email/password or continue with GitHub',
    'auth.login.logoAlt': 'Repo-Pulse Logo',
    'auth.login.form.email': 'Email',
    'auth.login.form.emailPlaceholder': 'name@example.com',
    'auth.login.form.password': 'Password',
    'auth.login.form.passwordPlaceholder': 'Enter your password',
    'auth.login.form.submit': 'Sign in',
    'auth.login.form.submitting': 'Signing in...',
    'auth.login.form.or': 'or',
    'auth.login.form.error.invalidEmail': 'Please enter a valid email address',
    'auth.login.form.error.passwordMin': 'Password must be at least 6 characters',
    'auth.login.form.error.invalidCredentials': 'Incorrect email or password',
    'auth.login.form.error.server': 'Service is temporarily unavailable, please try again later',
    'auth.login.form.error.network': 'Network error, please check your connection',
    'auth.login.form.error.generic': 'Sign-in failed, please try again',
    'auth.login.form.error.oauthFailed': 'OAuth sign-in failed, please try again',
    'auth.login.github': 'Continue with GitHub',
    'auth.login.notice': 'OAuth login will redirect you to GitHub authorization',
    'auth.login.oauthConfig.title': 'GitHub OAuth Setup',
    'auth.login.oauthConfig.helpButton': 'How to create?',
    'auth.login.oauthConfig.helpTitle': 'Create GitHub OAuth App',
    'auth.login.oauthConfig.helpDescription': 'Create an OAuth App in GitHub and paste the generated Client ID and Client Secret here.',
    'auth.login.oauthConfig.clientIdPlaceholder': 'GitHub Client ID',
    'auth.login.oauthConfig.clientSecretPlaceholder': 'GitHub Client Secret',
    'auth.login.oauthConfig.save': 'Save OAuth Config',
    'auth.login.oauthConfig.saving': 'Saving...',
    'auth.login.oauthConfig.success': 'OAuth configuration saved. You can now continue with GitHub.',
    'auth.login.oauthConfig.openGithub': 'Open GitHub OAuth App page',
    'auth.login.oauthConfig.callbackHint': 'Authorization callback URL:',
    'auth.login.oauthConfig.step1': 'Open GitHub Settings -> Developer settings -> OAuth Apps.',
    'auth.login.oauthConfig.step2': 'Click "New OAuth App" and fill in application information.',
    'auth.login.oauthConfig.step3': 'Set Authorization callback URL to the backend callback shown below.',
    'auth.login.oauthConfig.step4': 'Copy Client ID and generate Client Secret, then paste them in this form.',
    'auth.login.oauthConfig.error.invalidInput': 'Client ID and Client Secret are required.',
    'auth.login.oauthConfig.error.server': 'Failed to save OAuth configuration, please try again later.',
    'auth.login.oauthConfig.error.network': 'Network error while saving OAuth configuration.',
    'auth.login.oauthConfig.error.generic': 'Unable to save OAuth configuration.',
    'auth.callback.title': 'Signing in',
    'auth.callback.description': 'Validating your authorization and loading workspace',
    'auth.actions.logout': 'Sign out',

    // Landing
    'landing.nav.features': 'Features',
    'landing.nav.testimonials': 'Testimonials',
    'landing.nav.signIn': 'Sign In',
    'landing.nav.getStarted': 'Get Started',
    'landing.hero.badge': 'Now with AI Code Review',
    'landing.hero.title.prefix': 'AI-Powered',
    'landing.hero.title.highlight': 'Code Intelligence',
    'landing.hero.title.suffix': 'for Modern Teams',
    'landing.hero.description': 'Get instant insights into your codebase. From vulnerability detection to DORA metrics, Repo-Pulse is your AI development companion.',
    'landing.hero.primaryCta': 'Start Free Trial',
    'landing.hero.secondaryCta': 'View on GitHub',
    'landing.hero.trustedByPrefix': 'Trusted by',
    'landing.hero.trustedBySuffix': 'developers',
    'landing.preview.analysisComplete': 'AI Analysis Complete',
    'landing.preview.analysisResult': 'Found 2 security issues and 3 performance optimizations',
    'landing.preview.securityAlert': 'Security Alert',
    'landing.preview.securityMessage': 'Potential SQL injection vulnerability in auth.js:42',
    'landing.preview.deploymentFrequency': 'Deployment Frequency',
    'landing.stats.repositories': 'Repositories Analyzed',
    'landing.stats.lines': 'Lines of Code Processed',
    'landing.stats.uptime': 'Uptime SLA',
    'landing.stats.rating': 'User Rating',
    'landing.features.title': 'Everything you need to ship better code',
    'landing.features.description': 'From AI-powered analysis to team collaboration, Repo-Pulse provides the tools you need to build high-quality software faster.',
    'landing.features.items.analysis.title': 'AI-Powered Analysis',
    'landing.features.items.analysis.description': 'Get instant insights into your code with advanced AI that understands context and intent.',
    'landing.features.items.risk.title': 'Risk Detection',
    'landing.features.items.risk.description': 'Identify security vulnerabilities and high-risk changes before they reach production.',
    'landing.features.items.dora.title': 'DORA Metrics',
    'landing.features.items.dora.description': 'Track deployment frequency, lead time, and team productivity with industry-standard metrics.',
    'landing.features.items.notifications.title': 'Smart Notifications',
    'landing.features.items.notifications.description': 'Stay informed with intelligent alerts delivered to Slack, Email, or DingTalk.',
    'landing.features.items.dashboard.title': 'Real-time Dashboard',
    'landing.features.items.dashboard.description': 'Visualize your codebase health and team activity in a beautiful, intuitive interface.',
    'landing.features.items.reports.title': 'Auto Reports',
    'landing.features.items.reports.description': 'Generate weekly and monthly reports automatically to share with your team.',
    'landing.testimonials.title': 'Loved by developers worldwide',
    'landing.testimonials.description': 'See what teams are saying about Repo-Pulse',
    'landing.testimonials.items.0.quote': "Repo-Pulse has transformed how we review code. The AI insights catch issues we'd miss, and the DORA metrics help us continuously improve.",
    'landing.testimonials.items.0.author': 'Sarah Chen',
    'landing.testimonials.items.0.role': 'Tech Lead at Stripe',
    'landing.testimonials.items.1.quote': 'The risk detection feature alone has saved us countless hours. We caught a critical security vulnerability before it went live.',
    'landing.testimonials.items.1.author': 'Michael Park',
    'landing.testimonials.items.1.role': 'Engineering Manager at Netflix',
    'landing.testimonials.items.2.quote': 'Finally, a tool that understands developer workflows. The smart notifications mean I only get alerted when it actually matters.',
    'landing.testimonials.items.2.author': 'Emily Rodriguez',
    'landing.testimonials.items.2.role': 'Senior Developer at GitHub',
    'landing.cta.title': 'Ready to transform your code review process?',
    'landing.cta.description': 'Join thousands of developers who are shipping better code faster with Repo-Pulse.',
    'landing.cta.primary': 'Get Started Free',
    'landing.cta.secondary': 'Schedule Demo',
    'landing.footer.product.title': 'Product',
    'landing.footer.product.features': 'Features',
    'landing.footer.product.pricing': 'Pricing',
    'landing.footer.product.integrations': 'Integrations',
    'landing.footer.product.changelog': 'Changelog',
    'landing.footer.company.title': 'Company',
    'landing.footer.company.about': 'About',
    'landing.footer.company.blog': 'Blog',
    'landing.footer.company.careers': 'Careers',
    'landing.footer.company.contact': 'Contact',
    'landing.footer.resources.title': 'Resources',
    'landing.footer.resources.documentation': 'Documentation',
    'landing.footer.resources.api': 'API Reference',
    'landing.footer.resources.community': 'Community',
    'landing.footer.resources.support': 'Support',
    'landing.footer.legal.title': 'Legal',
    'landing.footer.legal.privacy': 'Privacy',
    'landing.footer.legal.terms': 'Terms',
    'landing.footer.legal.security': 'Security',
    'landing.footer.copyright': '© 2025 Repo-Pulse. All rights reserved.',

    // Dashboard
    'dashboard.page.title': 'Dashboard',
    'dashboard.page.description': 'Overview of repository activity and risk signals',
    'dashboard.hero.description': 'Real-time insights into your codebase health and team productivity',
    'dashboard.scope.label': 'Scope',
    'dashboard.empty.title': 'No repository connected yet',
    'dashboard.empty.description': 'No active repository connected. Connect or enable one to load dashboard data.',
    'dashboard.empty.action': 'Go to Repositories',
    'dashboard.filters.last7Days': 'Last 7 Days',
    'dashboard.actions.liveView': 'Live View',
    'dashboard.actions.viewAll': 'View All',
    'dashboard.sections.weeklyActivity': 'Weekly Activity',
    'dashboard.sections.riskDistribution': 'Risk Distribution',
    'dashboard.sections.doraMetrics': 'DORA Metrics',
    'dashboard.sections.recentActivity': 'Recent Activity',
    'dashboard.sections.teamContributions': 'Team Contributions',
    'dashboard.risk.low': 'Low',
    'dashboard.risk.medium': 'Medium',
    'dashboard.risk.high': 'High',
    'dashboard.dora.deploymentFrequency': 'Deployment Frequency',
    'dashboard.dora.leadTime': 'Lead Time for Changes',
    'dashboard.dora.changeFailureRate': 'Change Failure Rate',
    'dashboard.dora.timeToRecovery': 'Time to Recovery',
    'dashboard.error.partialLoadFailed': 'Failed to load part of dashboard data.',
    'dashboard.repo.fallback': 'repository',
    'dashboard.scope.title': 'Current Data Scope',
    'dashboard.scope.description': 'Dashboard metrics are based on the selected repository.',
    'dashboard.cards.repositories': 'Active Repositories',
    'dashboard.cards.events': 'Total Events',
    'dashboard.cards.pendingApprovals': 'Pending Approvals',
    'dashboard.cards.unreadNotifications': 'Unread Notifications',
    'dashboard.charts.title': 'Event Type Distribution',
    'dashboard.charts.description': 'Breakdown of recent events by type',
    'dashboard.charts.count': 'Count',
    'dashboard.charts.empty': 'No chart data available yet.',
    'dashboard.events.title': 'Recent Events',
    'dashboard.events.description': 'Latest events from the selected repository',
    'dashboard.events.empty': 'No recent events yet.',
    'dashboard.events.badges.pr': 'PR',
    'dashboard.events.badges.issue': 'Issue',
    'dashboard.events.badges.push': 'Push',
    'dashboard.events.badges.other': 'Other',
    'dashboard.error.loadFailed': 'Failed to load dashboard data.',
    'dashboard.error.retry': 'Retry',

    // Repositories
    'repositories.page.title': 'Repositories',
    'repositories.page.description': 'Manage monitored repositories and sync latest events',
    'repositories.toolbar.title': 'Repository Management',
    'repositories.toolbar.description': 'Filter monitored repositories or add new ones from Git providers',
    'repositories.toolbar.searchPlaceholder': 'Search by repository name',
    'repositories.filters.all': 'All',
    'repositories.filters.active': 'Active',
    'repositories.filters.inactive': 'Inactive',
    'repositories.actions.add': 'Add Repository',
    'repositories.actions.enable': 'Enable',
    'repositories.actions.disable': 'Disable',
    'repositories.actions.sync': 'Sync',
    'repositories.actions.open': 'Open',
    'repositories.actions.remove': 'Remove',
    'repositories.repo.active': 'Active',
    'repositories.repo.inactive': 'Inactive',
    'repositories.repo.neverSynced': 'Never synced',
    'repositories.repo.eventCount': 'Events',
    'repositories.dialog.title': 'Add Repository',
    'repositories.dialog.description': 'Choose a source and add repository to monitor',
    'repositories.dialog.tabs.search': 'Search',
    'repositories.dialog.tabs.my': 'My Repositories',
    'repositories.dialog.tabs.starred': 'Starred',
    'repositories.dialog.searchLabel': 'Search keyword',
    'repositories.dialog.searchPlaceholder': 'Input owner/repo keyword',
    'repositories.dialog.empty': 'No repositories found.',
    'repositories.dialog.noDescription': 'No description',
    'repositories.dialog.addButton': 'Add',
    'repositories.dialog.enableButton': 'Enable',
    'repositories.dialog.added': 'Added',
    'repositories.dialog.notAdded': 'Not Added',
    'repositories.dialog.close': 'Close',
    'repositories.empty.list': 'No repository matched current filters.',
    'repositories.error.loadFailed': 'Failed to load repositories.',
    'repositories.error.retry': 'Retry',

    // Notifications
    'notifications.page.title': 'Notifications',
    'notifications.page.description': 'Track recent alerts and adjust notification preferences',
    'notifications.list.title': 'Notification Feed',
    'notifications.list.description': 'Review recent alerts from monitored repositories',
    'notifications.tabs.all': 'All',
    'notifications.tabs.unread': 'Unread',
    'notifications.actions.markAllRead': 'Mark all as read',
    'notifications.actions.markRead': 'Mark as read',
    'notifications.actions.delete': 'Delete',
    'notifications.badges.unread': 'Unread',
    'notifications.empty.title': 'No notifications',
    'notifications.empty.description': 'You are all caught up.',
    'notifications.error.loadFailed': 'Failed to load notifications.',
    'notifications.error.retry': 'Retry',
    'notifications.channels.email': 'Email',
    'notifications.channels.dingtalk': 'DingTalk',
    'notifications.channels.feishu': 'Feishu',
    'notifications.channels.webhook': 'Webhook',
    'notifications.channels.inApp': 'In-App',
    'notifications.settings.title': 'Notification Preferences',
    'notifications.settings.description': 'Configure channels and event subscriptions',
    'notifications.settings.channels': 'Channels',
    'notifications.settings.events': 'Event Types',
    'notifications.settings.event.highRisk': 'High risk changes',
    'notifications.settings.event.prUpdates': 'PR updates',
    'notifications.settings.event.analysisComplete': 'Analysis complete',
    'notifications.settings.event.weeklyReport': 'Weekly reports',
    'notifications.settings.email': 'Notification email',
    'notifications.settings.emailPlaceholder': 'Enter email for notifications',
    'notifications.settings.webhook': 'Webhook URL',
    'notifications.settings.webhookPlaceholder': 'https://example.com/webhook',
    'notifications.settings.save': 'Save preferences',
    'notifications.settings.saving': 'Saving...',
    'notifications.settings.focus.badge': 'Default focus',
    'notifications.settings.focus.title': 'Choose how much activity should reach you by default',
    'notifications.settings.focus.description': 'Most teams can start here and only add exceptions for unusual cases later.',
    'notifications.settings.focus.levels.all.title': 'All updates',
    'notifications.settings.focus.levels.all.description': 'Receive broad repository activity, including routine changes and lower-signal updates.',
    'notifications.settings.focus.levels.all.badge': 'Most coverage',
    'notifications.settings.focus.levels.important.title': 'Important updates',
    'notifications.settings.focus.levels.important.description': 'Focus on meaningful changes without following every small event.',
    'notifications.settings.focus.levels.important.badge': 'Recommended',
    'notifications.settings.focus.levels.focused.title': 'Only high-signal updates',
    'notifications.settings.focus.levels.focused.description': 'Keep notifications quieter and reserve alerts for the highest-value events.',
    'notifications.settings.focus.levels.focused.badge': 'Quiet mode',
    'notifications.settings.templates.badge': 'Quick templates',
    'notifications.settings.templates.title': 'Start with a common noise-reduction pattern',
    'notifications.settings.templates.description': 'Pick one of these starting points first. We will turn the selected template into an editable exception rule in the next step.',
    'notifications.settings.templates.actions.use': 'Use as a starting point',
    'notifications.settings.templates.actions.selected': 'Selected',
    'notifications.settings.templates.selectedReady.title': 'Template ready for the next step',
    'notifications.settings.draft.badge': 'Draft rule',
    'notifications.settings.draft.title': 'Edit this exception before saving it',
    'notifications.settings.draft.description': 'You can adjust the name, action, and status now. We will connect this draft to real filter persistence in the next step.',
    'notifications.settings.draft.previewLabel': 'Current effect',
    'notifications.settings.draft.previewExclude': 'If saved like this, matching events would be muted.',
    'notifications.settings.draft.previewInclude': 'If saved like this, matching events would always keep notifying you.',
    'notifications.settings.draft.fields.name': 'Rule name',
    'notifications.settings.draft.fields.action': 'Action',
    'notifications.settings.draft.fields.description': 'Internal note',
    'notifications.settings.draft.fields.enabled': 'Enable this draft',
    'notifications.settings.draft.enabledHint': 'Turn it off if you want to keep the draft around without activating it later.',
    'notifications.settings.draft.actions.exclude': "Don't notify me",
    'notifications.settings.draft.actions.include': 'Keep notifying me',
    'notifications.settings.draft.actions.clear': 'Clear draft',
    'notifications.settings.draft.actions.next': 'Keep this draft',
    'notifications.settings.templates.items.ignoreBots.title': 'Ignore bot activity',
    'notifications.settings.templates.items.ignoreBots.description': 'Mute automated accounts so the notification feed stays focused on human work.',
    'notifications.settings.templates.items.ignoreBots.badge': 'Automation',
    'notifications.settings.templates.items.ignoreBots.summary': "Blocks notifications when the author looks like a bot account.",
    'notifications.settings.templates.items.ignoreBots.draftName': 'Ignore bot activity',
    'notifications.settings.templates.items.ignoreBots.draftDescription': 'Mute events created by automated accounts.',
    'notifications.settings.templates.items.ignorePushes.title': 'Mute push events',
    'notifications.settings.templates.items.ignorePushes.description': 'Reduce routine commit noise when push activity is already visible somewhere else.',
    'notifications.settings.templates.items.ignorePushes.badge': 'Routine updates',
    'notifications.settings.templates.items.ignorePushes.summary': "Blocks notifications when the event type is related to pushes.",
    'notifications.settings.templates.items.ignorePushes.draftName': 'Mute push events',
    'notifications.settings.templates.items.ignorePushes.draftDescription': 'Suppress routine push activity by default.',
    'notifications.settings.templates.items.ignoreLowRisk.title': 'Ignore low-risk changes',
    'notifications.settings.templates.items.ignoreLowRisk.description': 'Keep the inbox focused on events that need stronger attention.',
    'notifications.settings.templates.items.ignoreLowRisk.badge': 'Risk-based',
    'notifications.settings.templates.items.ignoreLowRisk.summary': "Blocks notifications when the risk level is low.",
    'notifications.settings.templates.items.ignoreLowRisk.draftName': 'Ignore low-risk changes',
    'notifications.settings.templates.items.ignoreLowRisk.draftDescription': 'Suppress low-risk events to keep focus on more important changes.',
    'notifications.settings.templates.items.ignoreComments.title': 'Mute comment chatter',
    'notifications.settings.templates.items.ignoreComments.description': 'Reduce discussion noise from comment-heavy threads and routine follow-ups.',
    'notifications.settings.templates.items.ignoreComments.badge': 'Conversation noise',
    'notifications.settings.templates.items.ignoreComments.summary': "Blocks notifications when the event type is comment-focused.",
    'notifications.settings.templates.items.ignoreComments.draftName': 'Mute comment chatter',
    'notifications.settings.templates.items.ignoreComments.draftDescription': 'Suppress comment-heavy threads and routine discussion updates.',
  },
  zh: {
    // Header
    'search.placeholder': '搜索文档...',
    'search.short': '搜索...',
    
    // Navigation
    'nav.overview': '概览',
    'nav.requirements': '需求分析',
    'nav.features': '核心功能',
    'nav.architecture': '架构设计',
    'nav.userScenarios': '用户场景',
    'nav.roadmap': '路线图',
    'nav.appendix': '附录',
    
    // Sub-nav
    'nav.userPersonas': '用户画像',
    'nav.painPoints': '痛点分析',
    'nav.marketResearch': '市场调研',
    'nav.dataListening': '数据监听',
    'nav.aiAnalysis': 'AI分析引擎',
    'nav.filtering': '过滤与订阅',
    'nav.approval': '审批工作流',
    'nav.notification': '智能通知',
    'nav.dashboard': '仪表板与分析',
    'nav.reporting': '自动报告',
    'nav.comparison': '仓库对比',
    'nav.systemDesign': '系统设计',
    'nav.techStack': '技术栈',
    'nav.dataFlow': '数据流',
    'nav.personalMode': '个人模式',
    'nav.teamMode': '团队模式',
    'nav.managerMode': '管理者模式',
    'nav.glossary': '术语表',
    'nav.references': '参考资料',
    
    // Overview
    'overview.title': 'Repo-Pulse 文档',
    'overview.subtitle': 'AI驱动的研发效能平台 — 将分散的仓库信息转化为结构化、可理解、可行动的洞察。',
    'overview.whatIs.title': '什么是 Repo-Pulse？',
    'overview.whatIs.description1': 'Repo-Pulse 是一个面向软件开发团队的AI驱动SaaS平台。它监听Git仓库活动（Issues、Pull Requests、Commits），对信息进行语义分析和风险评估，并通过可视化和智能通知呈现 — 帮助开发者和团队高效跟踪项目进展。',
    'overview.whatIs.description2': '与传统的代码审查工具不同，Repo-Pulse不仅仅分析代码质量。它将碎片化、冗余的代码信息转化为结构化、可理解、可决策的数据，使团队从"阅读代码更新"转变为"理解关键信息并做出决策"。',
    'overview.value.title': '核心价值主张',
    'overview.value.reduce': '减少信息过载',
    'overview.value.reduce.desc': 'AI自动过滤噪音并突出关键变更，将信息处理成本降低70%。',
    'overview.value.intelligent': '智能理解',
    'overview.value.intelligent.desc': '对代码变更进行语义分析，而不仅仅是关键词匹配。理解修改背后的业务含义。',
    'overview.value.risk': '风险预防',
    'overview.value.risk.desc': '在问题进入生产环境之前，自动识别高风险变更、安全漏洞和潜在问题。',
    'overview.features.title': '核心功能概览',
    'overview.quickStart.title': '快速开始',
    'overview.quickStart.step1': '连接您的GitHub或GitLab仓库',
    'overview.quickStart.step2': '配置AI分析偏好和通知规则',
    'overview.quickStart.step3': '开始接收智能摘要和洞察',
    'overview.users.title': '适用人群',
    'overview.users.individual': '个人开发者',
    'overview.users.individual.desc': '高效跟踪多个开源项目，不被通知淹没',
    'overview.users.team': '开发团队',
    'overview.users.team.desc': '通过AI辅助分析提高代码审查效率，降低风险',
    'overview.users.manager': '工程管理者',
    'overview.users.manager.desc': '数据驱动的团队生产力、代码质量趋势和项目健康度洞察',
    
    // Features
    'features.title': '核心功能',
    'features.subtitle': '智能研发效能管理的完整功能集',
    'features.overview.title': '功能概览',
    'features.checklist.title': '完整功能清单',
    'features.checklist.subtitle': '供开发人员参考的详细功能列表',
    
    // Requirements
    'requirements.title': '需求分析',
    'requirements.subtitle': '理解用户需求、痛点和市场格局',
    'requirements.personas.title': '用户画像',
    'requirements.painPoints.title': '痛点分析',
    'requirements.market.title': '市场调研',
    
    // Architecture
    'architecture.title': '架构设计',
    'architecture.subtitle': '系统设计、技术选择和数据流',
    
    // User Scenarios
    'scenarios.title': '用户场景',
    'scenarios.subtitle': '不同用户如何与Repo-Pulse交互',
    
    // Roadmap
    'roadmap.title': '路线图',
    'roadmap.subtitle': '开发时间表和未来计划',
    
    // Appendix
    'appendix.title': '附录',
    'appendix.subtitle': '附加资源和参考资料',
    
    // Common
    'common.readMore': '阅读更多',
    'common.learnMore': '了解更多',
    'common.getStarted': '开始使用',
    'common.viewDetails': '查看详情',
    'common.comingSoon': '即将推出',
    'common.inProgress': '进行中',
    'common.completed': '已完成',
    'common.planned': '计划中',

    // App shell
    'app.layout.title': '工作台',
    'app.layout.subtitle': 'AI 仓库监控',
    'app.layout.description': '集中查看仓库、事件与 AI 洞察',
    'app.layout.menu': '打开菜单',
    'app.layout.notifications': '通知',
    'app.layout.github': 'GitHub',
    'app.layout.docs': '文档',
    'app.layout.support': '支持',
    'app.search.placeholder': '搜索仓库、Issue、PR...',
    'app.language.switch': '切换语言',
    'app.language.english': 'English',
    'app.language.chinese': '中文',
    'app.user.unknown': '未知用户',
    'app.user.noEmail': '暂无邮箱',

    // App navigation
    'app.nav.dashboard': '仪表板',
    'app.nav.repositories': '仓库',
    'app.nav.analysis': 'AI 分析',
    'app.nav.approvals': '审批',
    'app.nav.notifications': '通知',
    'app.nav.reports': '报告',
    'app.nav.settings': '设置',

    // Auth
    'auth.login.title': '登录 Repo-Pulse',
    'auth.login.description': '使用邮箱密码登录，或使用 GitHub 账号继续',
    'auth.login.logoAlt': 'Repo-Pulse 标志',
    'auth.login.form.email': '邮箱',
    'auth.login.form.emailPlaceholder': 'name@example.com',
    'auth.login.form.password': '密码',
    'auth.login.form.passwordPlaceholder': '请输入密码',
    'auth.login.form.submit': '登录',
    'auth.login.form.submitting': '登录中...',
    'auth.login.form.or': '或',
    'auth.login.form.error.invalidEmail': '请输入有效的邮箱地址',
    'auth.login.form.error.passwordMin': '密码至少需要 6 位',
    'auth.login.form.error.invalidCredentials': '账号或密码错误',
    'auth.login.form.error.server': '服务暂时不可用，请稍后重试',
    'auth.login.form.error.network': '网络异常，请检查网络连接',
    'auth.login.form.error.generic': '登录失败，请重试',
    'auth.login.form.error.oauthFailed': 'OAuth 登录失败，请重试',
    'auth.login.github': '使用 GitHub 登录',
    'auth.login.notice': '点击后会跳转到 GitHub 授权页面',
    'auth.login.oauthConfig.title': 'GitHub OAuth 配置',
    'auth.login.oauthConfig.helpButton': '如何创建？',
    'auth.login.oauthConfig.helpTitle': '创建 GitHub OAuth 应用',
    'auth.login.oauthConfig.helpDescription': '在 GitHub 创建 OAuth 应用后，将生成的 Client ID 与 Client Secret 填入此处。',
    'auth.login.oauthConfig.clientIdPlaceholder': 'GitHub Client ID',
    'auth.login.oauthConfig.clientSecretPlaceholder': 'GitHub Client Secret',
    'auth.login.oauthConfig.save': '保存 OAuth 配置',
    'auth.login.oauthConfig.saving': '保存中...',
    'auth.login.oauthConfig.success': 'OAuth 配置已保存，现在可以继续使用 GitHub 登录。',
    'auth.login.oauthConfig.openGithub': '打开 GitHub OAuth 应用创建页',
    'auth.login.oauthConfig.callbackHint': '授权回调地址：',
    'auth.login.oauthConfig.step1': '打开 GitHub Settings -> Developer settings -> OAuth Apps。',
    'auth.login.oauthConfig.step2': '点击 New OAuth App，填写应用信息。',
    'auth.login.oauthConfig.step3': '将 Authorization callback URL 设置为下方后端回调地址。',
    'auth.login.oauthConfig.step4': '复制 Client ID 并生成 Client Secret，粘贴到本页面。',
    'auth.login.oauthConfig.error.invalidInput': 'Client ID 和 Client Secret 不能为空。',
    'auth.login.oauthConfig.error.server': 'OAuth 配置保存失败，请稍后重试。',
    'auth.login.oauthConfig.error.network': '保存 OAuth 配置时网络异常。',
    'auth.login.oauthConfig.error.generic': '无法保存 OAuth 配置。',
    'auth.callback.title': '登录中',
    'auth.callback.description': '正在校验授权并加载工作台',
    'auth.actions.logout': '退出登录',

    // Landing
    'landing.nav.features': '功能',
    'landing.nav.testimonials': '用户评价',
    'landing.nav.signIn': '登录',
    'landing.nav.getStarted': '开始使用',
    'landing.hero.badge': '现已支持 AI 代码审查',
    'landing.hero.title.prefix': 'AI 驱动的',
    'landing.hero.title.highlight': '代码智能',
    'landing.hero.title.suffix': '为现代团队而生',
    'landing.hero.description': '即时洞察你的代码库，从漏洞检测到 DORA 指标，Repo-Pulse 是你的 AI 研发助手。',
    'landing.hero.primaryCta': '开始免费试用',
    'landing.hero.secondaryCta': '在 GitHub 查看',
    'landing.hero.trustedByPrefix': '已被',
    'landing.hero.trustedBySuffix': '开发者信赖',
    'landing.preview.analysisComplete': 'AI 分析已完成',
    'landing.preview.analysisResult': '发现 2 个安全问题和 3 个性能优化点',
    'landing.preview.securityAlert': '安全告警',
    'landing.preview.securityMessage': '在 auth.js:42 发现潜在 SQL 注入风险',
    'landing.preview.deploymentFrequency': '部署频率',
    'landing.stats.repositories': '已分析仓库',
    'landing.stats.lines': '已处理代码行数',
    'landing.stats.uptime': '可用性 SLA',
    'landing.stats.rating': '用户评分',
    'landing.features.title': '你需要的一切都在这里',
    'landing.features.description': '从 AI 分析到团队协作，Repo-Pulse 提供高质量交付所需的完整能力。',
    'landing.features.items.analysis.title': 'AI 分析',
    'landing.features.items.analysis.description': '通过理解上下文与意图的 AI 引擎，快速获得代码洞察。',
    'landing.features.items.risk.title': '风险检测',
    'landing.features.items.risk.description': '在上线前识别安全漏洞和高风险变更。',
    'landing.features.items.dora.title': 'DORA 指标',
    'landing.features.items.dora.description': '用行业标准指标跟踪部署频率、交付周期和团队效率。',
    'landing.features.items.notifications.title': '智能通知',
    'landing.features.items.notifications.description': '通过 Slack、邮件或钉钉接收真正关键的提醒。',
    'landing.features.items.dashboard.title': '实时仪表板',
    'landing.features.items.dashboard.description': '用直观界面可视化代码健康度与团队活动。',
    'landing.features.items.reports.title': '自动报告',
    'landing.features.items.reports.description': '自动生成周报/月报，便于团队同步。',
    'landing.testimonials.title': '开发者共同推荐',
    'landing.testimonials.description': '看看团队如何评价 Repo-Pulse',
    'landing.testimonials.items.0.quote': 'Repo-Pulse 彻底改变了我们的代码评审方式。AI 洞察能发现我们容易忽略的问题，DORA 指标也帮助我们持续优化。',
    'landing.testimonials.items.0.author': 'Sarah Chen',
    'landing.testimonials.items.0.role': 'Stripe 技术负责人',
    'landing.testimonials.items.1.quote': '仅风险检测功能就帮我们节省了大量时间。我们在上线前拦截了一个关键安全漏洞。',
    'landing.testimonials.items.1.author': 'Michael Park',
    'landing.testimonials.items.1.role': 'Netflix 工程经理',
    'landing.testimonials.items.2.quote': '终于有真正理解开发流程的工具了。智能通知让我只在关键时刻被打扰。',
    'landing.testimonials.items.2.author': 'Emily Rodriguez',
    'landing.testimonials.items.2.role': 'GitHub 高级开发工程师',
    'landing.cta.title': '准备好升级你的代码评审流程了吗？',
    'landing.cta.description': '加入成千上万名开发者，用 Repo-Pulse 更快交付更高质量代码。',
    'landing.cta.primary': '免费开始',
    'landing.cta.secondary': '预约演示',
    'landing.footer.product.title': '产品',
    'landing.footer.product.features': '功能',
    'landing.footer.product.pricing': '价格',
    'landing.footer.product.integrations': '集成',
    'landing.footer.product.changelog': '更新日志',
    'landing.footer.company.title': '公司',
    'landing.footer.company.about': '关于我们',
    'landing.footer.company.blog': '博客',
    'landing.footer.company.careers': '招聘',
    'landing.footer.company.contact': '联系我们',
    'landing.footer.resources.title': '资源',
    'landing.footer.resources.documentation': '文档',
    'landing.footer.resources.api': 'API 参考',
    'landing.footer.resources.community': '社区',
    'landing.footer.resources.support': '支持',
    'landing.footer.legal.title': '法律',
    'landing.footer.legal.privacy': '隐私',
    'landing.footer.legal.terms': '条款',
    'landing.footer.legal.security': '安全',
    'landing.footer.copyright': '© 2025 Repo-Pulse。保留所有权利。',

    // Dashboard
    'dashboard.page.title': '仪表板',
    'dashboard.page.description': '仓库活动与风险信号总览',
    'dashboard.hero.description': '实时洞察代码库健康度与团队产能',
    'dashboard.scope.label': '范围',
    'dashboard.empty.title': '还没有接入仓库',
    'dashboard.empty.description': '当前没有启用中的仓库，请先连接或启用仓库以加载仪表板数据。',
    'dashboard.empty.action': '前往仓库页',
    'dashboard.filters.last7Days': '最近 7 天',
    'dashboard.actions.liveView': '实时视图',
    'dashboard.actions.viewAll': '查看全部',
    'dashboard.sections.weeklyActivity': '周活动趋势',
    'dashboard.sections.riskDistribution': '风险分布',
    'dashboard.sections.doraMetrics': 'DORA 指标',
    'dashboard.sections.recentActivity': '最近活动',
    'dashboard.sections.teamContributions': '团队贡献',
    'dashboard.risk.low': '低',
    'dashboard.risk.medium': '中',
    'dashboard.risk.high': '高',
    'dashboard.dora.deploymentFrequency': '部署频率',
    'dashboard.dora.leadTime': '变更交付周期',
    'dashboard.dora.changeFailureRate': '变更失败率',
    'dashboard.dora.timeToRecovery': '平均恢复时长',
    'dashboard.error.partialLoadFailed': '仪表板部分数据加载失败。',
    'dashboard.repo.fallback': '仓库',
    'dashboard.scope.title': '当前数据范围',
    'dashboard.scope.description': '仪表板指标基于当前选中的仓库。',
    'dashboard.cards.repositories': '活跃仓库数',
    'dashboard.cards.events': '事件总数',
    'dashboard.cards.pendingApprovals': '待审批',
    'dashboard.cards.unreadNotifications': '未读通知',
    'dashboard.charts.title': '事件类型分布',
    'dashboard.charts.description': '最近事件按类型拆分',
    'dashboard.charts.count': '数量',
    'dashboard.charts.empty': '暂无可展示的图表数据。',
    'dashboard.events.title': '最近事件',
    'dashboard.events.description': '来自当前仓库的最新事件',
    'dashboard.events.empty': '暂无最近事件。',
    'dashboard.events.badges.pr': '合并请求',
    'dashboard.events.badges.issue': '议题',
    'dashboard.events.badges.push': '推送',
    'dashboard.events.badges.other': '其他',
    'dashboard.error.loadFailed': '加载仪表板数据失败。',
    'dashboard.error.retry': '重试',

    // Repositories
    'repositories.page.title': '仓库',
    'repositories.page.description': '管理监控中的仓库并同步最新事件',
    'repositories.toolbar.title': '仓库管理',
    'repositories.toolbar.description': '筛选已监控仓库，或从代码平台添加新仓库',
    'repositories.toolbar.searchPlaceholder': '按仓库名称搜索',
    'repositories.filters.all': '全部',
    'repositories.filters.active': '启用',
    'repositories.filters.inactive': '停用',
    'repositories.actions.add': '添加仓库',
    'repositories.actions.enable': '启用',
    'repositories.actions.disable': '停用',
    'repositories.actions.sync': '同步',
    'repositories.actions.open': '打开',
    'repositories.actions.remove': '移除',
    'repositories.repo.active': '启用',
    'repositories.repo.inactive': '停用',
    'repositories.repo.neverSynced': '未同步',
    'repositories.repo.eventCount': '事件数',
    'repositories.dialog.title': '添加仓库',
    'repositories.dialog.description': '选择来源并添加需要监控的仓库',
    'repositories.dialog.tabs.search': '搜索',
    'repositories.dialog.tabs.my': '我的仓库',
    'repositories.dialog.tabs.starred': '已加星标',
    'repositories.dialog.searchLabel': '搜索关键词',
    'repositories.dialog.searchPlaceholder': '输入 owner/repo 关键词',
    'repositories.dialog.empty': '未找到仓库。',
    'repositories.dialog.noDescription': '暂无描述',
    'repositories.dialog.addButton': '添加',
    'repositories.dialog.enableButton': '启用',
    'repositories.dialog.added': '已添加',
    'repositories.dialog.notAdded': '未添加',
    'repositories.dialog.close': '关闭',
    'repositories.empty.list': '当前筛选条件下没有仓库。',
    'repositories.error.loadFailed': '加载仓库失败。',
    'repositories.error.retry': '重试',

    // Notifications
    'notifications.page.title': '通知',
    'notifications.page.description': '查看最新提醒并调整通知偏好',
    'notifications.list.title': '通知列表',
    'notifications.list.description': '查看来自监控仓库的最新提醒',
    'notifications.tabs.all': '全部',
    'notifications.tabs.unread': '未读',
    'notifications.actions.markAllRead': '全部标记已读',
    'notifications.actions.markRead': '标记已读',
    'notifications.actions.delete': '删除',
    'notifications.badges.unread': '未读',
    'notifications.empty.title': '暂无通知',
    'notifications.empty.description': '当前没有需要处理的通知。',
    'notifications.error.loadFailed': '加载通知失败。',
    'notifications.error.retry': '重试',
    'notifications.channels.email': '邮件',
    'notifications.channels.dingtalk': '钉钉',
    'notifications.channels.feishu': '飞书',
    'notifications.channels.webhook': 'Webhook',
    'notifications.channels.inApp': '站内通知',
    'notifications.settings.title': '通知偏好',
    'notifications.settings.description': '配置通知渠道和事件订阅',
    'notifications.settings.channels': '通知渠道',
    'notifications.settings.events': '事件类型',
    'notifications.settings.event.highRisk': '高风险变更',
    'notifications.settings.event.prUpdates': 'PR 更新',
    'notifications.settings.event.analysisComplete': '分析完成',
    'notifications.settings.event.weeklyReport': '周报推送',
    'notifications.settings.email': '通知邮箱',
    'notifications.settings.emailPlaceholder': '输入接收通知的邮箱',
    'notifications.settings.webhook': 'Webhook 地址',
    'notifications.settings.webhookPlaceholder': 'https://example.com/webhook',
    'notifications.settings.save': '保存偏好',
    'notifications.settings.saving': '保存中...',
    'notifications.settings.focus.badge': '默认焦点',
    'notifications.settings.focus.title': '先决定默认接收多少仓库动态',
    'notifications.settings.focus.description': '大多数团队先从这里选择一个默认级别就够了，少数特殊情况再补充例外规则。',
    'notifications.settings.focus.levels.all.title': '全部更新',
    'notifications.settings.focus.levels.all.description': '尽可能完整地接收仓库活动，包括日常更新和低信号提醒。',
    'notifications.settings.focus.levels.all.badge': '覆盖最全',
    'notifications.settings.focus.levels.important.title': '重要更新',
    'notifications.settings.focus.levels.important.description': '聚焦真正有价值的变化，不必跟着每一条小事件走。',
    'notifications.settings.focus.levels.important.badge': '推荐',
    'notifications.settings.focus.levels.focused.title': '仅高信号更新',
    'notifications.settings.focus.levels.focused.description': '让通知更安静，只在更值得关注的事件出现时提醒。',
    'notifications.settings.focus.levels.focused.badge': '安静模式',
    'notifications.settings.templates.badge': '快捷模板',
    'notifications.settings.templates.title': '先从常见降噪场景开始',
    'notifications.settings.templates.description': '先选一个模板作为起点。下一步我们会把当前选中的模板变成可编辑的例外规则。',
    'notifications.settings.templates.actions.use': '作为起点',
    'notifications.settings.templates.actions.selected': '已选择',
    'notifications.settings.templates.selectedReady.title': '模板已准备好进入下一步',
    'notifications.settings.draft.badge': '规则草稿',
    'notifications.settings.draft.title': '先把这条例外规则改顺手',
    'notifications.settings.draft.description': '你现在可以先调整名称、动作和启用状态。下一步我们会把这张草稿真正接到过滤规则保存链路里。',
    'notifications.settings.draft.previewLabel': '当前效果',
    'notifications.settings.draft.previewExclude': '如果按现在这样保存，命中的事件会被静音。',
    'notifications.settings.draft.previewInclude': '如果按现在这样保存，命中的事件会被强制保留通知。',
    'notifications.settings.draft.fields.name': '规则名称',
    'notifications.settings.draft.fields.action': '动作',
    'notifications.settings.draft.fields.description': '内部备注',
    'notifications.settings.draft.fields.enabled': '启用这张草稿',
    'notifications.settings.draft.enabledHint': '如果你想先保留草稿但暂时不生效，可以先关闭它。',
    'notifications.settings.draft.actions.exclude': '不要通知我',
    'notifications.settings.draft.actions.include': '继续通知我',
    'notifications.settings.draft.actions.clear': '清空草稿',
    'notifications.settings.draft.actions.next': '保留这张草稿',
    'notifications.settings.templates.items.ignoreBots.title': '忽略机器人活动',
    'notifications.settings.templates.items.ignoreBots.description': '把自动化账号的提醒静音，让通知更聚焦在人类协作上。',
    'notifications.settings.templates.items.ignoreBots.badge': '自动化',
    'notifications.settings.templates.items.ignoreBots.summary': '当作者看起来像机器人账号时，阻断通知。',
    'notifications.settings.templates.items.ignoreBots.draftName': '忽略机器人活动',
    'notifications.settings.templates.items.ignoreBots.draftDescription': '将自动化账号创建的事件静音。',
    'notifications.settings.templates.items.ignorePushes.title': '静音 push 事件',
    'notifications.settings.templates.items.ignorePushes.description': '如果你已经在别处关注提交记录，可以先压下日常 push 噪音。',
    'notifications.settings.templates.items.ignorePushes.badge': '日常更新',
    'notifications.settings.templates.items.ignorePushes.summary': '当事件类型和 push 相关时，阻断通知。',
    'notifications.settings.templates.items.ignorePushes.draftName': '静音 push 事件',
    'notifications.settings.templates.items.ignorePushes.draftDescription': '默认压下日常 push 活动提醒。',
    'notifications.settings.templates.items.ignoreLowRisk.title': '忽略低风险变更',
    'notifications.settings.templates.items.ignoreLowRisk.description': '让通知更聚焦在真正需要注意的事件上。',
    'notifications.settings.templates.items.ignoreLowRisk.badge': '按风险过滤',
    'notifications.settings.templates.items.ignoreLowRisk.summary': '当风险等级为低时，阻断通知。',
    'notifications.settings.templates.items.ignoreLowRisk.draftName': '忽略低风险变更',
    'notifications.settings.templates.items.ignoreLowRisk.draftDescription': '让低风险事件默认不再打扰你。',
    'notifications.settings.templates.items.ignoreComments.title': '静音评论噪音',
    'notifications.settings.templates.items.ignoreComments.description': '减少评论密集型讨论带来的提醒干扰。',
    'notifications.settings.templates.items.ignoreComments.badge': '讨论噪音',
    'notifications.settings.templates.items.ignoreComments.summary': '当事件类型以评论为主时，阻断通知。',
    'notifications.settings.templates.items.ignoreComments.draftName': '静音评论噪音',
    'notifications.settings.templates.items.ignoreComments.draftDescription': '减少评论密集型讨论线程带来的提醒。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
