/* eslint-disable react-refresh/only-export-components -- provider and consumer hook intentionally share one context */
import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Dashboard
    'dashboard.page.title': 'Dashboard',
    'dashboard.page.description': 'Overview of repository activity and risk signals',
    'dashboard.hero.description': 'Real-time insights into your codebase health and team productivity',
    'dashboard.scope.label': 'Scope',
    'dashboard.branch.all': 'All branches',
    'dashboard.branch.popover.title': 'Branch control',
    'dashboard.branch.popover.description': 'This slot is reserved for branch filters so scope and branch controls stay together.',
    'dashboard.branch.popover.currentLabel': 'Current branch scope',
    'dashboard.scope.placeholder': 'Select monitored repositories',
    'dashboard.scope.searchPlaceholder': 'Search repositories',
    'dashboard.scope.tabs.selected': 'In Scope',
    'dashboard.scope.tabs.all': 'All Repositories',
    'dashboard.scope.selectAll': 'Select All',
    'dashboard.scope.clear': 'Clear',
    'dashboard.scope.noSearchResult': 'No repositories found.',
    'dashboard.scope.emptySelectedTab': 'No repositories are in your monitoring scope yet.',
    'dashboard.scope.emptySelection': 'Choose one or more repositories to start monitoring this dashboard.',
    'dashboard.scope.row.allBranches': 'All branches',
    'dashboard.scope.row.notInScope': 'Not in scope',
    'dashboard.scope.branches.title': 'Branches',
    'dashboard.scope.branches.description': 'Select specific branches for this repository, or leave it on all branches.',
    'dashboard.scope.branches.loading': 'Loading available branches…',
    'dashboard.scope.branches.empty': 'No branch list is available yet. New events will still be tracked under all branches by default.',
    'dashboard.empty.title': 'No repository connected yet',
    'dashboard.empty.description': 'No active repository connected. Connect or enable one to load dashboard data.',
    'dashboard.empty.action': 'Go to Repositories',
    'dashboard.filters.last7Days': 'Last 7 Days',
    'dashboard.actions.liveView': 'Live View',
    'dashboard.actions.viewAll': 'View All',
    'dashboard.sections.weeklyActivity': 'Weekly Activity',
    'dashboard.sections.riskDistribution': 'Risk Distribution',
    'dashboard.sections.doraMetrics': 'DORA Metrics',
    'dashboard.sections.recentActivity': 'Recent Activity',
    'dashboard.sections.teamContributions': 'Team Contributions',
    'dashboard.radar.insightsTitle': 'Radar Insights',
    'dashboard.radar.insightsDescription': 'D3-powered contributor capability and commit-time preference views for the selected scope.',
    'dashboard.radar.contributorTitle': 'Contributor Capability Radar',
    'dashboard.radar.hourlyTitle': '24-Hour Commit Preference',
    'dashboard.radar.contributorSelect': 'Select contributor',
    'dashboard.radar.emptyContributors': 'No contributor statistics available for this scope.',
    'dashboard.radar.emptyHourly': 'No commit-like events available for this scope.',
    'dashboard.radar.totalEvents': 'Total Events',
    'dashboard.radar.totalCommits': 'Total Commits',
    'dashboard.radar.activeDays': 'Active Days',
    'dashboard.radar.rawValue': 'Raw',
    'dashboard.radar.normalizedValue': 'Normalized',
    'dashboard.radar.peakHour': 'Peak Hour',
    'dashboard.radar.count': 'Count',
    'dashboard.radar.axes.commits': 'Commits',
    'dashboard.radar.axes.prs': 'PRs',
    'dashboard.radar.axes.issues': 'Issues',
    'dashboard.radar.axes.releases': 'Releases',
    'dashboard.radar.axes.engagement': 'Engagement',
    'dashboard.radar.axes.activeDays': 'Active Days',
    'projectRiver.loading': 'Loading repository river...',
    'projectRiver.error': 'Failed to load repository river data.',
    'projectRiver.unknownRepository': 'Repository',
    'projectRiver.subtitle': 'Project-river style flow map for commits, release signals, and contributor concentration in this repository.',
    'projectRiver.noDateRange': 'No activity window',
    'projectRiver.openGithub': 'Open GitHub',
    'projectRiver.exportSvg': 'Export SVG',
    'projectRiver.contributors': 'Contributors',
    'projectRiver.commits': 'Commits',
    'projectRiver.latestActivity': 'Latest activity',
    'projectRiver.signal.coverage': 'Coverage',
    'projectRiver.signal.warning': 'Warnings',
    'projectRiver.signal.stable': 'Stable signals',
    'projectRiver.topLabel': 'Top',
    'projectRiver.topAuto': 'Auto',
    'projectRiver.keyNodes': 'Key nodes',
    'projectRiver.otherContributors': 'Other contributors',
    'projectRiver.allHistory': 'All history',
    'projectRiver.granularity.day': 'Day',
    'projectRiver.granularity.week': 'Week',
    'projectRiver.granularity.month': 'Month',
    'projectRiver.eventTypes.push': 'Push',
    'projectRiver.eventTypes.pullRequest': 'Pull request',
    'projectRiver.eventTypes.issue': 'Issue',
    'projectRiver.eventTypes.release': 'Release',
    'projectRiver.eventTypes.security': 'Security',
    'projectRiver.eventTypes.other': 'Other',
    'projectRiver.keyNodeTypes.contributorFirstCommit': 'First commit',
    'projectRiver.keyNodeTypes.contributorExit': 'Contributor exit',
    'projectRiver.keyNodeTypes.activitySpike': 'Activity spike',
    'projectRiver.keyNodeTypes.activityDrop': 'Activity drop',
    'projectRiver.keyNodeTypes.majorRefactor': 'Major refactor',
    'projectRiver.keyNodeTypes.commitMilestone': 'Commit milestone',
    'projectRiver.keyNodeTypes.projectStart': 'Project start',
    'projectRiver.keyNodeTypes.projectArchived': 'Archived signal',
    'projectRiver.keyNodeTitles.contributor_first_commit': 'New contributor: {name}',
    'projectRiver.keyNodeTitles.contributor_exit': 'Core contributor inactive: {name}',
    'projectRiver.keyNodeTitles.activity_spike': 'Activity spike',
    'projectRiver.keyNodeTitles.activity_drop': 'Activity drop',
    'projectRiver.keyNodeTitles.major_refactor': 'Major refactor',
    'projectRiver.keyNodeTitles.commit_milestone': '{threshold} commits milestone',
    'projectRiver.keyNodeTitles.project_start': 'Project started',
    'projectRiver.keyNodeTitles.project_archived': 'Archived project signal',
    'projectRiver.keyNodeDescriptions.contributor_first_commit': '{name} reached {commits} commits after joining the project.',
    'projectRiver.keyNodeDescriptions.contributor_exit': '{name} has been quiet for {days} days after {commits} commits.',
    'projectRiver.keyNodeDescriptions.activity_spike': '{commits} commits landed in one window, z-score {zScore}.',
    'projectRiver.keyNodeDescriptions.activity_drop': 'Commit activity stayed below the baseline for {days} days.',
    'projectRiver.keyNodeDescriptions.major_refactor': '{lines} deleted lines exceeded the normal activity window.',
    'projectRiver.keyNodeDescriptions.commit_milestone': 'The repository reached {threshold} cumulative commits.',
    'projectRiver.keyNodeDescriptions.project_start': 'The first commit activity was recorded on {date}.',
    'projectRiver.keyNodeDescriptions.project_archived': 'No commits have been recorded for {daysSilent} days since {lastDate}.',
    'projectRiver.health.concentration': 'Concentrated Contributions',
    'projectRiver.health.concentrationEvidence': 'Top 3 contributors ({names}) account for {pct}% of commits',
    'projectRiver.health.activityDrop': 'Activity Drop',
    'projectRiver.health.activityDropEvidence': 'Daily average of {avg} commits over 90 days ({pct}% of prior baseline)',
    'projectRiver.health.codeChurn': 'Code Churn',
    'projectRiver.health.codeChurnEvidence': 'Average of {lines} lines changed per commit',
    'projectRiver.health.distributionGrowth': 'Contributor Growth',
    'projectRiver.health.distributionGrowthEvidence': 'Contributor count grew by {pct}% QoQ ({prev} → {curr})',
    'projectRiver.health.sustainedActivity': 'Sustained Activity',
    'projectRiver.health.sustainedActivityEvidenceToday': 'Active with commits in the last day',
    'projectRiver.health.sustainedActivityEvidence': 'Active with commits {days} days ago',
    'projectRiver.health.projectArchived': 'Inactive Project',
    'projectRiver.health.projectArchivedEvidence': 'Last commit on {lastDate}, silent for {daysSilent} days',
    'projectRiver.empty.noCommitData': 'No commit activity is available for the selected scope.',
    'projectRiver.empty.noCommitHint': 'Issue and notification markers can still be reviewed below; the river appears when push or commit events exist.',
    'projectRiver.eventsPanel': 'Key nodes',
    'projectRiver.eventsEmpty': 'No visible events for the selected filters.',
    'projectRiver.activeContributors': 'Active',
    'projectRiver.activeDays': 'Active days',
    'projectRiver.total': 'Total',
    'projectRiver.tooltip.commits': 'Commits',
    'projectRiver.tooltip.total': 'Total',
    'dashboard.activity.window': 'Shows activity in the selected scope over the last 7 days.',
    'dashboard.activity.emptyTitle': 'No activity in this window',
    'dashboard.activity.empty': 'No commits, pull requests, or issues have been recorded for the selected scope yet.',
    'dashboard.activity.emptyWithHistory': 'The selected scope has historical events, but none occurred in the last 7 days. Check Recent Activity for older items.',
    'dashboard.risk.low': 'Low',
    'dashboard.risk.medium': 'Medium',
    'dashboard.risk.high': 'High',
    'dashboard.dora.deploymentFrequency': 'Deployment Frequency',
    'dashboard.dora.leadTime': 'Lead Time for Changes',
    'dashboard.dora.changeFailureRate': 'Change Failure Rate',
    'dashboard.dora.timeToRecovery': 'Time to Recovery',
    'dashboard.error.partialLoadFailed': 'Failed to load part of dashboard data.',
    'dashboard.repo.fallback': 'repository',
    'dashboard.scope.title': 'Current Data Scope',
    'dashboard.scope.description': 'Dashboard metrics are based on the selected repositories.',
    'dashboard.cards.repositories': 'Monitored Repositories',
    'dashboard.cards.events': 'Total Events',
    'dashboard.cards.pendingApprovals': 'Pending Approvals',
    'dashboard.cards.unreadNotifications': 'Unread Notifications',
    'dashboard.charts.title': 'Event Type Distribution',
    'dashboard.charts.description': 'Breakdown of recent events by type',
    'dashboard.charts.count': 'Count',
    'dashboard.charts.empty': 'No chart data available yet.',
    'dashboard.events.title': 'Recent Events',
    'dashboard.events.description': 'Latest events from the selected repository',
    'dashboard.events.empty': 'No recent events yet.',
    'dashboard.events.badges.pr': 'PR',
    'dashboard.events.badges.issue': 'Issue',
    'dashboard.events.badges.push': 'Push',
    'dashboard.events.badges.other': 'Other',
    'dashboard.error.loadFailed': 'Failed to load dashboard data.',
    'dashboard.error.retry': 'Retry',

    // Repositories
    'repositories.page.title': 'Repositories',
    'repositories.page.description': 'Organize your repository inventory, decide what stays in scope, and sync the latest events',
    'repositories.toolbar.title': 'Repository Management',
    'repositories.toolbar.description': 'Search your repository inventory, add new sources, and keep your monitoring scope focused',
    'repositories.toolbar.searchPlaceholder': 'Search by repository name',
    'repositories.filters.all': 'All',
    'repositories.filters.active': 'Active',
    'repositories.filters.inactive': 'Inactive',
    'repositories.actions.add': 'Add Repository',
    'repositories.actions.addToScope': 'Add to Scope',
    'repositories.actions.enable': 'Enable',
    'repositories.actions.disable': 'Disable',
    'repositories.actions.sync': 'Sync',
    'repositories.actions.open': 'Open',
    'repositories.actions.remove': 'Remove',
    'repositories.actions.removeFromScope': 'Remove from Scope',
    'repositories.repo.active': 'Active',
    'repositories.repo.inactive': 'Inactive',
    'repositories.repo.neverSynced': 'Never synced',
    'repositories.repo.eventCount': 'Events',
    'repositories.scope.title': 'Monitoring Scope',
    'repositories.scope.description': 'These repositories drive your dashboard, alerts, and review queue.',
    'repositories.scope.empty': 'Nothing is in your monitoring scope yet. Add repositories here to focus your workspace.',
    'repositories.other.title': 'Other Repositories',
    'repositories.other.description': 'These repositories are connected, but currently excluded from your monitoring scope.',
    'repositories.other.empty': 'No additional repositories are waiting outside your monitoring scope.',
    'repositories.dialog.title': 'Add Repository',
    'repositories.dialog.description': 'Choose a source and add repository to monitor',
    'repositories.dialog.tabs.search': 'Search',
    'repositories.dialog.tabs.my': 'My Repositories',
    'repositories.dialog.tabs.starred': 'Starred',
    'repositories.dialog.searchLabel': 'Search keyword',
    'repositories.dialog.searchPlaceholder': 'Input owner/repo keyword',
    'repositories.dialog.empty': 'No repositories found.',
    'repositories.dialog.noDescription': 'No description',
    'repositories.dialog.addButton': 'Add',
    'repositories.dialog.addToScopeButton': 'Add to Scope',
    'repositories.dialog.enableButton': 'Enable',
    'repositories.dialog.added': 'Added',
    'repositories.dialog.inScope': 'In Scope',
    'repositories.dialog.notAdded': 'Not Added',
    'repositories.dialog.close': 'Close',
    'repositories.empty.list': 'No repository matched current filters.',
    'repositories.error.loadFailed': 'Failed to load repositories.',
    'repositories.error.retry': 'Retry',

    'notifications.settings.focus.badge': 'Default focus',
    'notifications.settings.focus.title': 'Choose how much activity should reach you by default',
    'notifications.settings.focus.description': 'Most teams can start here and only add exceptions for unusual cases later.',
    'notifications.settings.focus.levels.all.title': 'All updates',
    'notifications.settings.focus.levels.all.description': 'Receive broad repository activity, including routine changes and lower-signal updates.',
    'notifications.settings.focus.levels.all.badge': 'Most coverage',
    'notifications.settings.focus.levels.important.title': 'Important updates',
    'notifications.settings.focus.levels.important.description': 'Focus on meaningful changes without following every small event.',
    'notifications.settings.focus.levels.important.badge': 'Recommended',
    'notifications.settings.focus.levels.focused.title': 'Only high-signal updates',
    'notifications.settings.focus.levels.focused.description': 'Keep notifications quieter and reserve alerts for the highest-value events.',
    'notifications.settings.focus.levels.focused.badge': 'Quiet mode',
    'notifications.settings.templates.badge': 'Quick templates',
    'notifications.settings.templates.title': 'Start with a common noise-reduction pattern',
    'notifications.settings.templates.description': 'Pick one of these starting points first, then save it as an exception rule without leaving Settings.',
    'notifications.settings.templates.actions.use': 'Use as a starting point',
    'notifications.settings.templates.actions.selected': 'Selected',
    'notifications.settings.draft.badge': 'Draft rule',
    'notifications.settings.draft.title': 'Edit this exception before saving it',
    'notifications.settings.draft.description': 'Adjust the rule name, action, and enabled state here before saving it to your exception list.',
    'notifications.settings.draft.previewLabel': 'Current effect',
    'notifications.settings.draft.previewExclude': 'If saved like this, matching events would be muted.',
    'notifications.settings.draft.previewInclude': 'If saved like this, matching events would always keep notifying you.',
    'notifications.settings.draft.fields.name': 'Rule name',
    'notifications.settings.draft.fields.action': 'Action',
    'notifications.settings.draft.fields.description': 'Internal note',
    'notifications.settings.draft.fields.enabled': 'Enable this draft',
    'notifications.settings.draft.enabledHint': 'Turn it off if you want to keep the draft around without activating it later.',
    'notifications.settings.draft.actions.exclude': "Don't notify me",
    'notifications.settings.draft.actions.include': 'Keep notifying me',
    'notifications.settings.draft.actions.clear': 'Clear draft',
    'notifications.settings.draft.actions.next': 'Save exception rule',
    'notifications.settings.draft.actions.update': 'Update exception rule',
    'notifications.settings.rules.badge': 'Exception rules',
    'notifications.settings.rules.title': 'Your exception rules',
    'notifications.settings.rules.description': 'Rules here override your default notification focus whenever a matching event appears.',
    'notifications.settings.rules.emptyTitle': 'No exception rules yet',
    'notifications.settings.rules.emptyDescription': 'Choose a template above and save it to create your first exception rule.',
    'notifications.settings.rules.loading': 'Loading saved exception rules...',
    'notifications.settings.rules.customSummary': 'Uses custom matching conditions that do not map to one of the quick templates.',
    'notifications.settings.rules.errorTitle': 'Could not load exception rules',
    'notifications.settings.rules.errorDescription': 'Try refreshing the page or signing in again if the session has expired.',
    'notifications.settings.rules.saveSuccess': 'Exception rule saved.',
    'notifications.settings.rules.saveError': 'We could not save that exception rule.',
    'notifications.settings.rules.removeSuccess': 'Exception rule removed.',
    'notifications.settings.rules.removeError': 'We could not remove that exception rule.',
    'notifications.settings.rules.status.enabled': 'Enabled',
    'notifications.settings.rules.status.disabled': 'Disabled',
    'notifications.settings.rules.actions.edit': 'Edit',
    'notifications.settings.rules.actions.remove': 'Remove',
    'notifications.settings.templates.items.ignoreBots.title': 'Ignore bot activity',
    'notifications.settings.templates.items.ignoreBots.description': 'Mute automated accounts so the notification feed stays focused on human work.',
    'notifications.settings.templates.items.ignoreBots.badge': 'Automation',
    'notifications.settings.templates.items.ignoreBots.summary': "Blocks notifications when the author looks like a bot account.",
    'notifications.settings.templates.items.ignoreBots.draftName': 'Ignore bot activity',
    'notifications.settings.templates.items.ignoreBots.draftDescription': 'Mute events created by automated accounts.',
    'notifications.settings.templates.items.ignorePushes.title': 'Mute push events',
    'notifications.settings.templates.items.ignorePushes.description': 'Reduce routine commit noise when push activity is already visible somewhere else.',
    'notifications.settings.templates.items.ignorePushes.badge': 'Routine updates',
    'notifications.settings.templates.items.ignorePushes.summary': "Blocks notifications when the event type is related to pushes.",
    'notifications.settings.templates.items.ignorePushes.draftName': 'Mute push events',
    'notifications.settings.templates.items.ignorePushes.draftDescription': 'Suppress routine push activity by default.',
    'notifications.settings.templates.items.ignoreLowRisk.title': 'Ignore low-risk changes',
    'notifications.settings.templates.items.ignoreLowRisk.description': 'Keep the inbox focused on events that need stronger attention.',
    'notifications.settings.templates.items.ignoreLowRisk.badge': 'Risk-based',
    'notifications.settings.templates.items.ignoreLowRisk.summary': "Blocks notifications when the risk level is low.",
    'notifications.settings.templates.items.ignoreLowRisk.draftName': 'Ignore low-risk changes',
    'notifications.settings.templates.items.ignoreLowRisk.draftDescription': 'Suppress low-risk events to keep focus on more important changes.',
    'notifications.settings.templates.items.ignoreComments.title': 'Mute comment chatter',
    'notifications.settings.templates.items.ignoreComments.description': 'Reduce discussion noise from comment-heavy threads and routine follow-ups.',
    'notifications.settings.templates.items.ignoreComments.badge': 'Conversation noise',
    'notifications.settings.templates.items.ignoreComments.summary': "Blocks notifications when the event type is comment-focused.",
    'notifications.settings.templates.items.ignoreComments.draftName': 'Mute comment chatter',
    'notifications.settings.templates.items.ignoreComments.draftDescription': 'Suppress comment-heavy threads and routine discussion updates.',

    // Reports
    'reports.page.title': 'Reports',
    'reports.page.description': 'Automated insights and analytics for your codebase',
    'reports.page.thisWeek': 'This Week',
    'reports.page.exportPdf': 'Export PDF',
    'reports.sidebar.title': 'Recent Reports',
    'reports.sidebar.generate': 'Generate Custom Report',
    'reports.title.weekly': 'Weekly Code Quality Report',
    'reports.title.security': 'Security Audit Report',
    'reports.title.team': 'Team Performance Report',
    'reports.detail.badge.weekly': 'weekly',
    'reports.detail.badge.security': 'security',
    'reports.detail.badge.team': 'team',
    'reports.charts.activity': 'Activity',
    'reports.charts.issues': 'Issues',
    'reports.charts.trends': 'Trends',
    'reports.charts.emptyActivity': 'No activity data available',
    'reports.charts.emptyIssues': 'No issue data available',
    'reports.charts.emptyTrends': 'No trend data available',
    'reports.empty': 'No repository activity data available yet. Add a repository to get started.',
    'reports.issues.security': 'Security',
    'reports.issues.performance': 'Performance',
    'reports.issues.codeQuality': 'Code Quality',
    'reports.issues.documentation': 'Documentation',
    'reports.issues.other': 'Other',
    'reports.metrics.issues': 'Issues',
    'reports.metrics.resolved': 'Resolved',
    'reports.metrics.prs': 'PRs',
    'reports.metrics.critical': 'Critical',
    'reports.metrics.high': 'High',
    'reports.metrics.medium': 'Medium',
    'reports.metrics.velocity': 'Velocity',
    'reports.metrics.reviewTime': 'Review Time',
    'reports.metrics.commits': 'Commits',

    // Settings
    'settings.page.title': 'Settings',
    'settings.page.description': 'Manage your account and preferences',
    'settings.save': 'Save Changes',
    'settings.saved': 'Saved!',
    'settings.tabs.profile': 'Profile',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.integrations': 'Integrations',
    'settings.tabs.security': 'Security',
    'settings.tabs.ai': 'AI',
    'settings.profile.title': 'Profile Information',
    'settings.profile.changeAvatar': 'Change Avatar',
    'settings.profile.avatarHint': 'JPG, PNG or GIF. Max 2MB.',
    'settings.profile.avatarUrl': 'Avatar URL',
    'settings.profile.fullName': 'Full Name',
    'settings.profile.or': 'or',
    'settings.profile.uploadAvatar': 'Change Avatar',
    'settings.profile.avatarUploaded': 'Avatar uploaded',
    'settings.profile.restoreAvatar': 'Restore GitHub avatar',
    'settings.profile.avatarRestored': 'GitHub avatar restored',
    'settings.profile.username': 'Username',
    'settings.profile.email': 'Email',
    'settings.profile.company': 'Company',
    'settings.profile.bio': 'Bio',
    'settings.profile.save': 'Save Settings',
    'settings.profile.saving': 'Saving...',
    'settings.profile.saved': 'Profile saved',
    'settings.profile.saveFailed': 'Failed to save profile',
    'settings.integrations.title': 'Connected Accounts',
    'settings.integrations.connected': 'Connected',
    'settings.integrations.disconnect': 'Disconnect',
    'settings.integrations.connect': 'Connect',
    'settings.integrations.github.notConnected': 'Not connected',
    'settings.integrations.github.connectedAccount': 'Connected account',
    'settings.integrations.github.description': 'Use a GitHub personal access token for repository sync and webhook management.',
    'settings.integrations.github.token': 'Personal access token',
    'settings.integrations.github.placeholder': 'github_pat_...',
    'settings.integrations.github.updatePlaceholder': 'Paste a new token to replace the current one',
    'settings.integrations.github.save': 'Save token',
    'settings.integrations.github.update': 'Update token',
    'settings.integrations.github.test': 'Test',
    'settings.integrations.github.saved': 'GitHub token saved',
    'settings.integrations.github.syncCompleted': 'GitHub token saved · repository sync finished ({count} new)',
    'settings.integrations.github.syncPending': 'GitHub token saved · repositories are still syncing in the background',
    'settings.integrations.github.syncFailed': 'GitHub token saved, but repository sync failed — check the token scopes (repo / admin:repo_hook)',
    'settings.integrations.github.saveFailed': 'Unable to save GitHub token',
    'settings.integrations.github.tokenRequired': 'Enter a GitHub token',
    'settings.integrations.github.testOk': 'GitHub token is valid',
    'settings.integrations.github.testFailed': 'GitHub token test failed',
    'settings.integrations.github.disconnected': 'GitHub disconnected',
    'settings.integrations.github.disconnectFailed': 'Unable to disconnect GitHub',
    'settings.integrations.feishu.title': 'Feishu Bot',
    'settings.integrations.feishu.subtitle': 'Configure the bot, then bind users and chats.',
    'settings.integrations.feishu.ready': 'Ready',
    'settings.integrations.feishu.notConfigured': 'Not configured',
    'settings.integrations.feishu.configure': 'Configure',
    'settings.integrations.feishu.manage': 'Manage',
    'settings.integrations.feishu.tab.credentials': 'Credentials',
    'settings.integrations.feishu.tab.test': 'Test',
    'settings.integrations.feishu.tab.binding': 'Bind',
    'settings.integrations.feishu.tab.subscriptions': 'Subscribe',
    'settings.integrations.feishu.appId': 'App ID',
    'settings.integrations.feishu.appSecret': 'App Secret',
    'settings.integrations.feishu.validation': 'App ID and App Secret are required',
    'settings.integrations.feishu.saved': 'Feishu credentials saved',
    'settings.integrations.feishu.save': 'Save',
    'settings.integrations.feishu.test': 'Test connection',
    'settings.integrations.feishu.testPush': 'Test event card',
    'settings.integrations.feishu.generateCode': 'Generate code',
    'settings.integrations.feishu.copy': 'Copy',
    'settings.integrations.feishu.copied': 'Copied',
    'settings.integrations.feishu.noPairingCode': 'No pairing code',
    'settings.integrations.feishu.bindingHint': 'Generate a code, then send it to the bot.',
    'settings.integrations.feishu.bindingReady': 'Feishu chat bound',
    'settings.integrations.feishu.expiresAt': 'Expires at {time}',
    'settings.integrations.feishu.branches': 'Branches',
    'settings.integrations.feishu.subscriptionEnabled': 'Enable push',
    'settings.integrations.feishu.repositories': 'Repositories',
    'settings.integrations.feishu.allRepositories': 'All monitored repositories',
    'settings.integrations.feishu.allRepositoriesHint': 'Empty selection means all active repositories.',
    'settings.integrations.feishu.repositorySearch': 'Search repositories',
    'settings.integrations.feishu.repositoryMode.monitored': 'Monitored',
    'settings.integrations.feishu.repositoryMode.all': 'All',
    'settings.integrations.feishu.noRepositoryMatches': 'No matching repositories',
    'settings.integrations.feishu.noRepositories': 'No active repositories yet',
    'settings.integrations.feishu.noAllRepositories': 'No repositories yet',
    'settings.integrations.feishu.repositoryNotSelected': 'Not subscribed',
    'settings.integrations.feishu.defaultChat': 'Default chat',
    'settings.integrations.feishu.subscriptionSaved': 'Subscription saved',
    'settings.integrations.feishu.saveSubscriptions': 'Save subscription',
    'settings.integrations.feishu.guide': 'View guide',
    'settings.integrations.feishu.guideStep1': 'Create a self-built app in Feishu Open Platform.',
    'settings.integrations.feishu.guideStep2': 'Enable bot capability.',
    'settings.integrations.feishu.guideStep3': 'Batch-enable permissions, then publish the app version.',
    'settings.integrations.feishu.guideStep4': 'In Events and Callbacks, choose long connection event receiving.',
    'settings.integrations.feishu.guideStep5': 'Add im.message.receive_v1, then test the connection here.',
    'settings.integrations.feishu.permissionScopes': 'Permission JSON',
    'settings.integrations.feishu.nextStepSecret': 'Check App Secret and bot permissions.',
    'settings.integrations.feishu.stage.configured': 'Config',
    'settings.integrations.feishu.stage.credential_valid': 'Secret',
    'settings.integrations.feishu.stage.ws_connected': 'Long conn',
    'settings.integrations.feishu.stage.bot_reachable': 'Bot',
    'settings.integrations.feishu.stage.subscription_ready': 'Chats',
    'settings.integrations.feishu.stageState.verified': 'Ready',
    'settings.integrations.feishu.stageState.missing': 'Missing',
    'settings.integrations.feishu.stageState.unknown': 'Pending',
    'settings.integrations.feishu.stageState.error': 'Check',
    'settings.integrations.feishu.event.PUSH': 'Push',
    'settings.integrations.feishu.event.PR_OPENED': 'PR opened',
    'settings.integrations.feishu.event.PR_MERGED': 'PR merged',
    'settings.integrations.feishu.event.PR_CLOSED': 'PR closed',
    'settings.integrations.feishu.event.PR_REVIEW': 'PR review',
    'settings.integrations.feishu.event.ISSUE_OPENED': 'Issue opened',
    'settings.integrations.feishu.event.ISSUE_CLOSED': 'Issue closed',
    'settings.integrations.feishu.event.ISSUE_COMMENT': 'Issue comment',
    'settings.integrations.feishu.event.RELEASE': 'Release',
    'settings.integrations.feishu.event.BRANCH_CREATED': 'Branch created',
    'settings.integrations.feishu.event.BRANCH_DELETED': 'Branch deleted',
    'settings.integrations.apiKeys': 'API Keys',
    'settings.integrations.generateKey': 'Generate New Key',
    'settings.integrations.revoke': 'Revoke',
    'settings.integrations.created': 'Created:',
    'settings.integrations.lastUsed': 'Last used:',
    'settings.security.password': 'Password',
    'settings.security.appLock': 'App lock',
    'settings.security.appLockDescription': 'Repo-Pulse opens directly by default. Enable this only when you want a password check on every desktop launch.',
    'settings.security.enabled': 'Startup verification on',
    'settings.security.disabled': 'Startup verification off',
    'settings.security.loading': 'Loading security settings...',
    'settings.security.currentPassword': 'Current Password',
    'settings.security.setPassword': 'Set app lock password',
    'settings.security.newPassword': 'New Password',
    'settings.security.confirmPassword': 'Confirm New Password',
    'settings.security.updatePassword': 'Update Password',
    'settings.security.enableLock': 'Enable startup verification',
    'settings.security.disableLock': 'Disable startup verification',
    'settings.security.restartHint': 'The new setting takes effect the next time the desktop app starts.',
    'settings.security.passwordTooShort': 'Password must be at least 6 characters',
    'settings.security.passwordMismatch': 'The passwords do not match',
    'settings.security.invalidPassword': 'Current password is incorrect',
    'settings.security.operationFailed': 'Unable to update app lock',
    'settings.security.enabledSuccess': 'Startup verification enabled',
    'settings.security.changedSuccess': 'App lock password updated',
    'settings.security.disabledSuccess': 'Startup verification disabled',
    'settings.security.dangerZone': 'Danger Zone',
    'settings.security.deleteAccount': 'Delete Account',
    'settings.security.deleteDescription': 'Permanently delete your account and all data',
    'settings.security.deleteButton': 'Delete Account',

    // Settings - Notifications tab
    'settings.notifications.badge.controls': 'Notification Controls',
    'settings.notifications.title': 'Reduce noise without missing important updates',
    'settings.notifications.description': 'Notification settings now combine delivery channels, default focus, and exception rules in one place.',
    'settings.notifications.section.delivery': 'Delivery',
    'settings.notifications.section.deliveryDesc': 'First decide which channels are allowed to reach you.',
    'settings.notifications.channels.cardTitle': 'Delivery channels',
    'settings.notifications.channels.cardDesc': 'Choose where alerts should arrive.',
    'settings.notifications.channels.header': 'Notification Channels',
    'settings.notifications.channels.headerDesc': 'Configure how you want to receive notifications',
    'settings.notifications.channels.email': 'Email',
    'settings.notifications.channels.emailDesc': 'Receive updates via email',
    'settings.notifications.channels.dingtalk': 'DingTalk',
    'settings.notifications.channels.dingtalkDesc': 'Send to DingTalk webhook',
    'settings.notifications.channels.feishu': 'Feishu',
    'settings.notifications.channels.feishuDesc': 'Send to Feishu webhook',
    'settings.notifications.channels.wecom': 'WeCom',
    'settings.notifications.channels.wecomDesc': 'Send to Enterprise WeChat (WeCom) webhook',
    'settings.notifications.channels.wechat': 'WeChat',
    'settings.notifications.channels.wechatDesc': 'Receive personal private chat notifications via bot',
    'settings.notifications.channels.inApp': 'In-App',
    'settings.notifications.channels.inAppDesc': 'Receive in-app notifications',
    'settings.notifications.channels.webhookUrl': 'Webhook URL',
    'settings.notifications.section.focus': 'Focus',
    'settings.notifications.section.focusDesc': 'Then decide which kinds of repository activity should still get through by default.',
    'settings.notifications.focus.cardTitle': 'Default notification focus',
    'settings.notifications.focus.cardDesc': 'This area will host the default level selector next.',
    'settings.notifications.focus.header': 'Notification Focus',
    'settings.notifications.focus.headerDesc': 'These toggles are the current baseline. Default levels and rule-based filtering will be added into this section next.',
    'settings.notifications.events.highRisk': 'High Risk Alerts',
    'settings.notifications.events.highRiskDesc': 'Critical security and performance issues',
    'settings.notifications.events.prUpdates': 'PR Updates',
    'settings.notifications.events.prUpdatesDesc': 'Pull request created, updated, or merged',
    'settings.notifications.events.analysisComplete': 'Analysis Complete',
    'settings.notifications.events.analysisCompleteDesc': 'AI analysis finished for a PR',
    'settings.notifications.events.weeklyReport': 'Weekly Reports',
    'settings.notifications.events.weeklyReportDesc': 'Weekly code quality summary',
    'settings.notifications.section.exceptions': 'Exceptions',
    'settings.notifications.section.exceptionsDesc': 'Quick templates and exception rules for fine-tuning noisy cases.',
    'settings.notifications.exceptions.cardTitle': 'Exception rules',
    'settings.notifications.exceptions.cardDesc': 'Templates and advanced filters will live here after the focus selector.',
    'settings.notifications.exceptions.incoming': 'Notification filtering is moving here',
    'settings.notifications.exceptions.incomingDesc': 'Next we will embed default focus levels, quick templates, and exception rules directly into this tab.',
    'settings.notifications.exceptions.planned': 'Planned modules',
    'settings.notifications.exceptions.plannedDesc': 'Default notification level, template shortcuts, readable exception rules, and advanced preview.',
    'settings.notifications.save': 'Save Notification Settings',
    'settings.notifications.saving': 'Saving...',
    'settings.notifications.saved': 'Saved!',

    // Settings - AI tab
    'settings.ai.title': 'AI Provider Configuration',
    'settings.ai.description': 'Configure your AI provider for code analysis',
    'settings.ai.provider': 'AI Provider',
    'settings.ai.providerPlaceholder': 'Select an AI provider',
    'settings.ai.apiKey': 'API Key',
    'settings.ai.apiKeyPlaceholder': 'Enter your API key',
    'settings.ai.apiKeyHint': 'Leave empty to keep the existing API key',
    'settings.ai.baseUrl': 'Base URL',
    'settings.ai.baseUrlPlaceholder': 'https://api.example.com/v1',
    'settings.ai.endpointPreview': 'Endpoint Preview',
    'settings.ai.testConnection': 'Test Connection',
    'settings.ai.testing': 'Testing...',
    'settings.ai.model': 'Model',
    'settings.ai.modelPlaceholder': 'Enter model name',
    'settings.ai.fetchModels': 'Fetch Models from Provider',
    'settings.ai.fetching': 'Fetching...',
    'settings.ai.availableModels': 'Available Models',
    'settings.ai.use': 'Use',
    'settings.ai.save': 'Save AI Config',
    'settings.ai.saving': 'Saving...',
    'settings.ai.saved': 'Saved!',


  },
  zh: {
    // Dashboard
    'dashboard.page.title': '仪表板',
    'dashboard.page.description': '仓库活动与风险信号总览',
    'dashboard.hero.description': '实时洞察代码库健康度与团队产能',
    'dashboard.scope.label': '范围',
    'dashboard.branch.all': '全部分支',
    'dashboard.branch.popover.title': '分支控制',
    'dashboard.branch.popover.description': '这里会承接分支筛选，让仓库范围和分支范围放在同一个操作区里。',
    'dashboard.branch.popover.currentLabel': '当前分支范围',
    'dashboard.scope.placeholder': '选择监视仓库',
    'dashboard.scope.searchPlaceholder': '搜索仓库',
    'dashboard.scope.tabs.selected': '已在监控范围',
    'dashboard.scope.tabs.all': '全部仓库',
    'dashboard.scope.selectAll': '全选',
    'dashboard.scope.clear': '清空',
    'dashboard.scope.noSearchResult': '没有匹配的仓库。',
    'dashboard.scope.emptySelectedTab': '当前监控范围里还没有仓库。',
    'dashboard.scope.emptySelection': '请选择一个或多个仓库，开始监视该看板的数据范围。',
    'dashboard.scope.row.allBranches': '全部分支',
    'dashboard.scope.row.notInScope': '未纳入监控范围',
    'dashboard.scope.branches.title': '分支范围',
    'dashboard.scope.branches.description': '可以为这个仓库单独选择分支；如果不选，则默认监控全部分支。',
    'dashboard.scope.branches.loading': '正在加载可选分支…',
    'dashboard.scope.branches.empty': '暂时还拿不到分支列表，但系统仍会默认按全部分支继续监控。',
    'dashboard.empty.title': '还没有接入仓库',
    'dashboard.empty.description': '当前没有启用中的仓库，请先连接或启用仓库以加载仪表板数据。',
    'dashboard.empty.action': '前往仓库页',
    'dashboard.filters.last7Days': '最近 7 天',
    'dashboard.actions.liveView': '实时视图',
    'dashboard.actions.viewAll': '查看全部',
    'dashboard.sections.weeklyActivity': '周活动趋势',
    'dashboard.sections.riskDistribution': '风险分布',
    'dashboard.sections.doraMetrics': 'DORA 指标',
    'dashboard.sections.recentActivity': '最近活动',
    'dashboard.sections.teamContributions': '团队贡献',
    'dashboard.radar.insightsTitle': '雷达洞察',
    'dashboard.radar.insightsDescription': '基于 D3 呈现当前范围的贡献者能力结构与 24 小时提交偏好。',
    'dashboard.radar.contributorTitle': '贡献者能力雷达图',
    'dashboard.radar.hourlyTitle': '24 小时提交偏好',
    'dashboard.radar.contributorSelect': '选择贡献者',
    'dashboard.radar.emptyContributors': '当前范围暂无贡献者统计数据。',
    'dashboard.radar.emptyHourly': '当前范围暂无提交类事件。',
    'dashboard.radar.totalEvents': '事件总数',
    'dashboard.radar.totalCommits': '提交总数',
    'dashboard.radar.activeDays': '活跃天数',
    'dashboard.radar.rawValue': '原始值',
    'dashboard.radar.normalizedValue': '归一化',
    'dashboard.radar.peakHour': '峰值时段',
    'dashboard.radar.count': '数量',
    'dashboard.radar.axes.commits': '代码提交',
    'dashboard.radar.axes.prs': '拉取请求',
    'dashboard.radar.axes.issues': '问题解决',
    'dashboard.radar.axes.releases': '版本发布',
    'dashboard.radar.axes.engagement': '活跃沟通',
    'dashboard.radar.axes.activeDays': '活跃天数',
    'projectRiver.loading': '正在加载仓库河流图...',
    'projectRiver.error': '仓库河流图数据加载失败。',
    'projectRiver.unknownRepository': '仓库',
    'projectRiver.subtitle': '复用 project-river 风格的提交河流、事件标记与贡献者集中度交互。',
    'projectRiver.noDateRange': '暂无活动窗口',
    'projectRiver.openGithub': '打开 GitHub',
    'projectRiver.exportSvg': '导出 SVG',
    'projectRiver.contributors': '贡献者',
    'projectRiver.commits': '提交',
    'projectRiver.latestActivity': '最近活动',
    'projectRiver.signal.coverage': '覆盖',
    'projectRiver.signal.warning': '预警',
    'projectRiver.signal.stable': '信号稳定',
    'projectRiver.topLabel': 'Top',
    'projectRiver.topAuto': '自动',
    'projectRiver.keyNodes': '关键节点',
    'projectRiver.otherContributors': '其他贡献者',
    'projectRiver.allHistory': '全部历史',
    'projectRiver.granularity.day': '按日',
    'projectRiver.granularity.week': '按周',
    'projectRiver.granularity.month': '按月',
    'projectRiver.eventTypes.push': 'Push',
    'projectRiver.eventTypes.pullRequest': 'PR',
    'projectRiver.eventTypes.issue': 'Issue',
    'projectRiver.eventTypes.release': 'Release',
    'projectRiver.eventTypes.security': '安全',
    'projectRiver.eventTypes.other': '其他',
    'projectRiver.keyNodeTypes.contributorFirstCommit': '首次提交',
    'projectRiver.keyNodeTypes.contributorExit': '贡献者离开',
    'projectRiver.keyNodeTypes.activitySpike': '活跃峰值',
    'projectRiver.keyNodeTypes.activityDrop': '活跃下降',
    'projectRiver.keyNodeTypes.majorRefactor': '重大重构',
    'projectRiver.keyNodeTypes.commitMilestone': '提交里程碑',
    'projectRiver.keyNodeTypes.projectStart': '项目启动',
    'projectRiver.keyNodeTypes.projectArchived': '归档信号',
    'projectRiver.keyNodeTitles.contributor_first_commit': '新贡献者：{name}',
    'projectRiver.keyNodeTitles.contributor_exit': '核心贡献者停止活跃：{name}',
    'projectRiver.keyNodeTitles.activity_spike': '活跃峰值',
    'projectRiver.keyNodeTitles.activity_drop': '活跃下降',
    'projectRiver.keyNodeTitles.major_refactor': '重大重构',
    'projectRiver.keyNodeTitles.commit_milestone': '{threshold} 次提交里程碑',
    'projectRiver.keyNodeTitles.project_start': '项目启动',
    'projectRiver.keyNodeTitles.project_archived': '项目归档信号',
    'projectRiver.keyNodeDescriptions.contributor_first_commit': '{name} 加入后累计达到 {commits} 次提交。',
    'projectRiver.keyNodeDescriptions.contributor_exit': '{name} 累计 {commits} 次提交后，已静默 {days} 天。',
    'projectRiver.keyNodeDescriptions.activity_spike': '该窗口记录 {commits} 次提交，z-score 为 {zScore}。',
    'projectRiver.keyNodeDescriptions.activity_drop': '提交活跃度连续 {days} 天低于基线。',
    'projectRiver.keyNodeDescriptions.major_refactor': '删除 {lines} 行，超过近期正常活动窗口。',
    'projectRiver.keyNodeDescriptions.commit_milestone': '仓库累计提交达到 {threshold} 次。',
    'projectRiver.keyNodeDescriptions.project_start': '首次提交活动记录于 {date}。',
    'projectRiver.keyNodeDescriptions.project_archived': '自 {lastDate} 以来已有 {daysSilent} 天未记录提交。',
    'projectRiver.health.concentration': '贡献集中',
    'projectRiver.health.concentrationEvidence': '前 3 位贡献者 ({names}) 占总提交的 {pct}%',
    'projectRiver.health.activityDrop': '活跃度下降',
    'projectRiver.health.activityDropEvidence': '近 90 天日均 {avg} 次提交，为前期日均的 {pct}%',
    'projectRiver.health.codeChurn': '代码动荡',
    'projectRiver.health.codeChurnEvidence': '平均每次提交变更 {lines} 行',
    'projectRiver.health.distributionGrowth': '贡献者增长',
    'projectRiver.health.distributionGrowthEvidence': '贡献者数量季度环比增长 {pct}%（{prev} → {curr}）',
    'projectRiver.health.sustainedActivity': '持续活跃',
    'projectRiver.health.sustainedActivityEvidenceToday': '最近一天内有提交',
    'projectRiver.health.sustainedActivityEvidence': '最近提交于 {days} 天前',
    'projectRiver.health.projectArchived': '项目归档',
    'projectRiver.health.projectArchivedEvidence': '最后提交于 {lastDate}，已静默 {daysSilent} 天',
    'projectRiver.empty.noCommitData': '当前筛选范围暂无提交活动。',
    'projectRiver.empty.noCommitHint': '下方仍可查看 Issue 与通知事件标记；出现 Push 或提交事件后会生成河流图。',
    'projectRiver.eventsPanel': '关键节点',
    'projectRiver.eventsEmpty': '当前筛选条件下没有可见事件。',
    'projectRiver.activeContributors': '活跃',
    'projectRiver.activeDays': '活跃天数',
    'projectRiver.total': '累计',
    'projectRiver.tooltip.commits': '提交',
    'projectRiver.tooltip.total': '总量',
    'dashboard.activity.window': '展示当前范围最近 7 天的活动。',
    'dashboard.activity.emptyTitle': '这个时间窗口暂无活动',
    'dashboard.activity.empty': '当前范围还没有记录到提交、合并请求或议题。',
    'dashboard.activity.emptyWithHistory': '当前范围有历史事件，但最近 7 天没有新活动。可在最近活动中查看更早的记录。',
    'dashboard.risk.low': '低',
    'dashboard.risk.medium': '中',
    'dashboard.risk.high': '高',
    'dashboard.dora.deploymentFrequency': '部署频率',
    'dashboard.dora.leadTime': '变更交付周期',
    'dashboard.dora.changeFailureRate': '变更失败率',
    'dashboard.dora.timeToRecovery': '平均恢复时长',
    'dashboard.error.partialLoadFailed': '仪表板部分数据加载失败。',
    'dashboard.repo.fallback': '仓库',
    'dashboard.scope.title': '当前数据范围',
    'dashboard.scope.description': '仪表板指标基于当前选中的仓库集合。',
    'dashboard.cards.repositories': '监视仓库数',
    'dashboard.cards.events': '事件总数',
    'dashboard.cards.pendingApprovals': '待审批',
    'dashboard.cards.unreadNotifications': '未读通知',
    'dashboard.charts.title': '事件类型分布',
    'dashboard.charts.description': '最近事件按类型拆分',
    'dashboard.charts.count': '数量',
    'dashboard.charts.empty': '暂无可展示的图表数据。',
    'dashboard.events.title': '最近事件',
    'dashboard.events.description': '来自当前仓库的最新事件',
    'dashboard.events.empty': '暂无最近事件。',
    'dashboard.events.badges.pr': '合并请求',
    'dashboard.events.badges.issue': '议题',
    'dashboard.events.badges.push': '推送',
    'dashboard.events.badges.other': '其他',
    'dashboard.error.loadFailed': '加载仪表板数据失败。',
    'dashboard.error.retry': '重试',

    // Repositories
    'repositories.page.title': '仓库',
    'repositories.page.description': '管理仓库清单、调整监控范围，并同步最新事件',
    'repositories.toolbar.title': '仓库管理',
    'repositories.toolbar.description': '搜索仓库清单、添加新的来源，并让监控范围保持聚焦',
    'repositories.toolbar.searchPlaceholder': '按仓库名称搜索',
    'repositories.filters.all': '全部',
    'repositories.filters.active': '启用',
    'repositories.filters.inactive': '停用',
    'repositories.actions.add': '添加仓库',
    'repositories.actions.addToScope': '加入监控范围',
    'repositories.actions.enable': '启用',
    'repositories.actions.disable': '停用',
    'repositories.actions.sync': '同步',
    'repositories.actions.open': '打开',
    'repositories.actions.remove': '移除',
    'repositories.actions.removeFromScope': '移出监控范围',
    'repositories.repo.active': '启用',
    'repositories.repo.inactive': '停用',
    'repositories.repo.neverSynced': '未同步',
    'repositories.repo.eventCount': '事件数',
    'repositories.scope.title': '监控范围',
    'repositories.scope.description': '这里的仓库会驱动仪表板、通知和待审批队列。',
    'repositories.scope.empty': '当前还没有仓库进入监控范围。先把需要重点关注的仓库放进来。',
    'repositories.other.title': '其他仓库',
    'repositories.other.description': '这些仓库已经接入系统，但暂时不在当前监控范围内。',
    'repositories.other.empty': '当前没有额外仓库留在监控范围之外。',
    'repositories.dialog.title': '添加仓库',
    'repositories.dialog.description': '选择来源并添加需要监控的仓库',
    'repositories.dialog.tabs.search': '搜索',
    'repositories.dialog.tabs.my': '我的仓库',
    'repositories.dialog.tabs.starred': '已加星标',
    'repositories.dialog.searchLabel': '搜索关键词',
    'repositories.dialog.searchPlaceholder': '输入 owner/repo 关键词',
    'repositories.dialog.empty': '未找到仓库。',
    'repositories.dialog.noDescription': '暂无描述',
    'repositories.dialog.addButton': '添加',
    'repositories.dialog.addToScopeButton': '加入监控范围',
    'repositories.dialog.enableButton': '启用',
    'repositories.dialog.added': '已添加',
    'repositories.dialog.inScope': '已在监控范围',
    'repositories.dialog.notAdded': '未添加',
    'repositories.dialog.close': '关闭',
    'repositories.empty.list': '当前筛选条件下没有仓库。',
    'repositories.error.loadFailed': '加载仓库失败。',
    'repositories.error.retry': '重试',

    'notifications.settings.focus.badge': '默认焦点',
    'notifications.settings.focus.title': '先决定默认接收多少仓库动态',
    'notifications.settings.focus.description': '大多数团队先从这里选择一个默认级别就够了，少数特殊情况再补充例外规则。',
    'notifications.settings.focus.levels.all.title': '全部更新',
    'notifications.settings.focus.levels.all.description': '尽可能完整地接收仓库活动，包括日常更新和低信号提醒。',
    'notifications.settings.focus.levels.all.badge': '覆盖最全',
    'notifications.settings.focus.levels.important.title': '重要更新',
    'notifications.settings.focus.levels.important.description': '聚焦真正有价值的变化，不必跟着每一条小事件走。',
    'notifications.settings.focus.levels.important.badge': '推荐',
    'notifications.settings.focus.levels.focused.title': '仅高信号更新',
    'notifications.settings.focus.levels.focused.description': '让通知更安静，只在更值得关注的事件出现时提醒。',
    'notifications.settings.focus.levels.focused.badge': '安静模式',
    'notifications.settings.templates.badge': '快捷模板',
    'notifications.settings.templates.title': '先从常见降噪场景开始',
    'notifications.settings.templates.description': '先选一个模板作为起点，然后直接在设置页里把它保存成例外规则。',
    'notifications.settings.templates.actions.use': '作为起点',
    'notifications.settings.templates.actions.selected': '已选择',
    'notifications.settings.draft.badge': '规则草稿',
    'notifications.settings.draft.title': '先把这条例外规则改顺手',
    'notifications.settings.draft.description': '先在这里调整规则名称、动作和启用状态，再把它保存到你的例外规则列表里。',
    'notifications.settings.draft.previewLabel': '当前效果',
    'notifications.settings.draft.previewExclude': '如果按现在这样保存，命中的事件会被静音。',
    'notifications.settings.draft.previewInclude': '如果按现在这样保存，命中的事件会被强制保留通知。',
    'notifications.settings.draft.fields.name': '规则名称',
    'notifications.settings.draft.fields.action': '动作',
    'notifications.settings.draft.fields.description': '内部备注',
    'notifications.settings.draft.fields.enabled': '启用这张草稿',
    'notifications.settings.draft.enabledHint': '如果你想先保留草稿但暂时不生效，可以先关闭它。',
    'notifications.settings.draft.actions.exclude': '不要通知我',
    'notifications.settings.draft.actions.include': '继续通知我',
    'notifications.settings.draft.actions.clear': '清空草稿',
    'notifications.settings.draft.actions.next': '保存例外规则',
    'notifications.settings.draft.actions.update': '更新例外规则',
    'notifications.settings.rules.badge': '例外规则',
    'notifications.settings.rules.title': '你的例外规则',
    'notifications.settings.rules.description': '这里的规则会覆盖默认通知焦点，在命中对应事件时按你的例外设置执行。',
    'notifications.settings.rules.emptyTitle': '还没有例外规则',
    'notifications.settings.rules.emptyDescription': '先在上面选择一个模板并保存，它就会成为你的第一条例外规则。',
    'notifications.settings.rules.loading': '正在加载已保存的例外规则...',
    'notifications.settings.rules.customSummary': '这条规则使用了快捷模板之外的自定义匹配条件。',
    'notifications.settings.rules.errorTitle': '例外规则加载失败',
    'notifications.settings.rules.errorDescription': '可以刷新页面重试；如果登录状态失效，请重新登录。',
    'notifications.settings.rules.saveSuccess': '例外规则已保存。',
    'notifications.settings.rules.saveError': '例外规则保存失败。',
    'notifications.settings.rules.removeSuccess': '例外规则已移除。',
    'notifications.settings.rules.removeError': '例外规则移除失败。',
    'notifications.settings.rules.status.enabled': '已启用',
    'notifications.settings.rules.status.disabled': '已停用',
    'notifications.settings.rules.actions.edit': '编辑',
    'notifications.settings.rules.actions.remove': '移除',
    'notifications.settings.templates.items.ignoreBots.title': '忽略机器人活动',
    'notifications.settings.templates.items.ignoreBots.description': '把自动化账号的提醒静音，让通知更聚焦在人类协作上。',
    'notifications.settings.templates.items.ignoreBots.badge': '自动化',
    'notifications.settings.templates.items.ignoreBots.summary': '当作者看起来像机器人账号时，阻断通知。',
    'notifications.settings.templates.items.ignoreBots.draftName': '忽略机器人活动',
    'notifications.settings.templates.items.ignoreBots.draftDescription': '将自动化账号创建的事件静音。',
    'notifications.settings.templates.items.ignorePushes.title': '静音 push 事件',
    'notifications.settings.templates.items.ignorePushes.description': '如果你已经在别处关注提交记录，可以先压下日常 push 噪音。',
    'notifications.settings.templates.items.ignorePushes.badge': '日常更新',
    'notifications.settings.templates.items.ignorePushes.summary': '当事件类型和 push 相关时，阻断通知。',
    'notifications.settings.templates.items.ignorePushes.draftName': '静音 push 事件',
    'notifications.settings.templates.items.ignorePushes.draftDescription': '默认压下日常 push 活动提醒。',
    'notifications.settings.templates.items.ignoreLowRisk.title': '忽略低风险变更',
    'notifications.settings.templates.items.ignoreLowRisk.description': '让通知更聚焦在真正需要注意的事件上。',
    'notifications.settings.templates.items.ignoreLowRisk.badge': '按风险过滤',
    'notifications.settings.templates.items.ignoreLowRisk.summary': '当风险等级为低时，阻断通知。',
    'notifications.settings.templates.items.ignoreLowRisk.draftName': '忽略低风险变更',
    'notifications.settings.templates.items.ignoreLowRisk.draftDescription': '让低风险事件默认不再打扰你。',
    'notifications.settings.templates.items.ignoreComments.title': '静音评论噪音',
    'notifications.settings.templates.items.ignoreComments.description': '减少评论密集型讨论带来的提醒干扰。',
    'notifications.settings.templates.items.ignoreComments.badge': '讨论噪音',
    'notifications.settings.templates.items.ignoreComments.summary': '当事件类型以评论为主时，阻断通知。',
    'notifications.settings.templates.items.ignoreComments.draftName': '静音评论噪音',
    'notifications.settings.templates.items.ignoreComments.draftDescription': '减少评论密集型讨论线程带来的提醒。',

    // Reports
    'reports.page.title': '报告',
    'reports.page.description': '代码库自动化洞察与分析',
    'reports.page.thisWeek': '本周',
    'reports.page.exportPdf': '导出 PDF',
    'reports.sidebar.title': '最近报告',
    'reports.sidebar.generate': '生成自定义报告',
    'reports.title.weekly': '每周代码质量报告',
    'reports.title.security': '安全审计报告',
    'reports.title.team': '团队效能报告',
    'reports.detail.badge.weekly': '周报',
    'reports.detail.badge.security': '安全',
    'reports.detail.badge.team': '团队',
    'reports.charts.activity': '活动',
    'reports.charts.issues': '问题',
    'reports.charts.trends': '趋势',
    'reports.charts.emptyActivity': '暂无可用的活动数据',
    'reports.charts.emptyIssues': '暂无可用的 Issue 数据',
    'reports.charts.emptyTrends': '暂无可用的趋势数据',
    'reports.empty': '还没有仓库活动数据。请添加一个仓库开始使用。',
    'reports.issues.security': '安全',
    'reports.issues.performance': '性能',
    'reports.issues.codeQuality': '代码质量',
    'reports.issues.documentation': '文档',
    'reports.issues.other': '其他',
    'reports.metrics.issues': '问题数',
    'reports.metrics.resolved': '已解决',
    'reports.metrics.prs': 'PR 数',
    'reports.metrics.critical': '严重',
    'reports.metrics.high': '高',
    'reports.metrics.medium': '中',
    'reports.metrics.velocity': '速度',
    'reports.metrics.reviewTime': '审查时间',
    'reports.metrics.commits': '提交数',

    // Settings
    'settings.page.title': '设置',
    'settings.page.description': '管理您的账号和偏好',
    'settings.save': '保存更改',
    'settings.saved': '已保存！',
    'settings.tabs.profile': '个人资料',
    'settings.tabs.notifications': '通知',
    'settings.tabs.integrations': '集成',
    'settings.tabs.security': '安全',
    'settings.tabs.ai': 'AI',
    'settings.profile.title': '个人信息',
    'settings.profile.changeAvatar': '更换头像',
    'settings.profile.avatarUrl': '头像链接',
    'settings.profile.or': '或',
    'settings.profile.uploadAvatar': '更改头像',
    'settings.profile.restoreAvatar': '恢复 GitHub 头像',
    'settings.profile.avatarRestored': 'GitHub 头像已恢复',
    'settings.profile.avatarUploaded': '头像已上传',
    'settings.profile.avatarHint': 'JPG、PNG 或 GIF。最大 2MB。',
    'settings.profile.fullName': '姓名',
    'settings.profile.username': '用户名',
    'settings.profile.email': '邮箱',
    'settings.profile.company': '公司',
    'settings.profile.bio': '个人简介',
    'settings.profile.save': '保存设置',
    'settings.profile.saving': '保存中...',
    'settings.profile.saved': '个人资料已保存',
    'settings.profile.saveFailed': '保存失败',
    'settings.integrations.title': '已连接账号',
    'settings.integrations.connected': '已连接',
    'settings.integrations.disconnect': '断开',
    'settings.integrations.connect': '连接',
    'settings.integrations.github.notConnected': '未连接',
    'settings.integrations.github.connectedAccount': '已连接账号',
    'settings.integrations.github.description': '使用 GitHub Personal Access Token 同步仓库并管理 webhook。',
    'settings.integrations.github.token': 'Personal Access Token',
    'settings.integrations.github.placeholder': 'github_pat_...',
    'settings.integrations.github.updatePlaceholder': '粘贴新 token 以替换当前连接',
    'settings.integrations.github.save': '保存 token',
    'settings.integrations.github.update': '更新 token',
    'settings.integrations.github.test': '测试',
    'settings.integrations.github.saved': 'GitHub token 已保存',
    'settings.integrations.github.syncCompleted': 'GitHub token 已保存，仓库同步完成（新增 {count} 个）',
    'settings.integrations.github.syncPending': 'GitHub token 已保存，仓库正在后台同步，稍后自动显示',
    'settings.integrations.github.syncFailed': 'GitHub token 已保存，但仓库同步失败，请检查 token 权限（repo / admin:repo_hook）',
    'settings.integrations.github.saveFailed': '无法保存 GitHub token',
    'settings.integrations.github.tokenRequired': '请输入 GitHub token',
    'settings.integrations.github.testOk': 'GitHub token 有效',
    'settings.integrations.github.testFailed': 'GitHub token 测试失败',
    'settings.integrations.github.disconnected': 'GitHub 已断开',
    'settings.integrations.github.disconnectFailed': '无法断开 GitHub',
    'settings.integrations.feishu.title': '飞书机器人',
    'settings.integrations.feishu.subtitle': '配置机器人，然后绑定用户和群聊。',
    'settings.integrations.feishu.ready': '已就绪',
    'settings.integrations.feishu.notConfigured': '未配置',
    'settings.integrations.feishu.configure': '配置',
    'settings.integrations.feishu.manage': '管理',
    'settings.integrations.feishu.tab.credentials': '凭证',
    'settings.integrations.feishu.tab.test': '测试',
    'settings.integrations.feishu.tab.binding': '绑定',
    'settings.integrations.feishu.tab.subscriptions': '订阅',
    'settings.integrations.feishu.appId': 'App ID',
    'settings.integrations.feishu.appSecret': 'App Secret',
    'settings.integrations.feishu.validation': '请填写 App ID 和 App Secret',
    'settings.integrations.feishu.saved': '飞书凭证已保存',
    'settings.integrations.feishu.save': '保存',
    'settings.integrations.feishu.test': '测试连接',
    'settings.integrations.feishu.testPush': '测试事件卡片',
    'settings.integrations.feishu.generateCode': '生成配对码',
    'settings.integrations.feishu.copy': '复制',
    'settings.integrations.feishu.copied': '已复制',
    'settings.integrations.feishu.noPairingCode': '暂无配对码',
    'settings.integrations.feishu.bindingHint': '生成配对码后，在飞书中发给机器人。',
    'settings.integrations.feishu.bindingReady': '飞书群聊已绑定',
    'settings.integrations.feishu.expiresAt': '{time} 过期',
    'settings.integrations.feishu.branches': '分支',
    'settings.integrations.feishu.subscriptionEnabled': '启用推送',
    'settings.integrations.feishu.repositories': '仓库',
    'settings.integrations.feishu.allRepositories': '全部已监控仓库',
    'settings.integrations.feishu.allRepositoriesHint': '未指定仓库时推送所有启用仓库。',
    'settings.integrations.feishu.repositorySearch': '搜索仓库',
    'settings.integrations.feishu.repositoryMode.monitored': '已监控',
    'settings.integrations.feishu.repositoryMode.all': '全部',
    'settings.integrations.feishu.noRepositoryMatches': '没有匹配的仓库',
    'settings.integrations.feishu.noRepositories': '暂无启用仓库',
    'settings.integrations.feishu.noAllRepositories': '暂无仓库',
    'settings.integrations.feishu.repositoryNotSelected': '未订阅',
    'settings.integrations.feishu.defaultChat': '默认群聊',
    'settings.integrations.feishu.subscriptionSaved': '订阅已保存',
    'settings.integrations.feishu.saveSubscriptions': '保存订阅',
    'settings.integrations.feishu.guide': '查看指引',
    'settings.integrations.feishu.guideStep1': '在飞书开放平台创建企业自建应用。',
    'settings.integrations.feishu.guideStep2': '开启机器人能力。',
    'settings.integrations.feishu.guideStep3': '批量开通权限，然后发布应用版本。',
    'settings.integrations.feishu.guideStep4': '在「事件与回调」中选择使用长连接接收事件。',
    'settings.integrations.feishu.guideStep5': '添加 im.message.receive_v1，然后回到这里测试连接。',
    'settings.integrations.feishu.permissionScopes': '权限 JSON',
    'settings.integrations.feishu.nextStepSecret': '检查 App Secret 和机器人权限。',
    'settings.integrations.feishu.stage.configured': '配置',
    'settings.integrations.feishu.stage.credential_valid': '密钥',
    'settings.integrations.feishu.stage.ws_connected': '长连接',
    'settings.integrations.feishu.stage.bot_reachable': '机器人',
    'settings.integrations.feishu.stage.subscription_ready': '群聊',
    'settings.integrations.feishu.stageState.verified': '就绪',
    'settings.integrations.feishu.stageState.missing': '缺失',
    'settings.integrations.feishu.stageState.unknown': '待确认',
    'settings.integrations.feishu.stageState.error': '需检查',
    'settings.integrations.feishu.event.PUSH': 'Push',
    'settings.integrations.feishu.event.PR_OPENED': 'PR 打开',
    'settings.integrations.feishu.event.PR_MERGED': 'PR 合并',
    'settings.integrations.feishu.event.PR_CLOSED': 'PR 关闭',
    'settings.integrations.feishu.event.PR_REVIEW': 'PR Review',
    'settings.integrations.feishu.event.ISSUE_OPENED': 'Issue 打开',
    'settings.integrations.feishu.event.ISSUE_CLOSED': 'Issue 关闭',
    'settings.integrations.feishu.event.ISSUE_COMMENT': 'Issue 评论',
    'settings.integrations.feishu.event.RELEASE': 'Release',
    'settings.integrations.feishu.event.BRANCH_CREATED': '分支创建',
    'settings.integrations.feishu.event.BRANCH_DELETED': '分支删除',
    'settings.integrations.apiKeys': 'API 密钥',
    'settings.integrations.generateKey': '生成新密钥',
    'settings.integrations.revoke': '吊销',
    'settings.integrations.created': '创建时间：',
    'settings.integrations.lastUsed': '上次使用：',
    'settings.security.password': '密码',
    'settings.security.appLock': '应用锁',
    'settings.security.appLockDescription': 'Repo-Pulse 默认直接进入工作台。仅在需要每次启动验证时开启应用锁。',
    'settings.security.enabled': '已开启启动验证',
    'settings.security.disabled': '未开启启动验证',
    'settings.security.loading': '正在加载安全设置…',
    'settings.security.currentPassword': '当前密码',
    'settings.security.setPassword': '设置应用锁密码',
    'settings.security.newPassword': '新密码',
    'settings.security.confirmPassword': '确认新密码',
    'settings.security.updatePassword': '更新密码',
    'settings.security.enableLock': '开启启动验证',
    'settings.security.disableLock': '关闭启动验证',
    'settings.security.restartHint': '新的设置将在下次启动桌面应用时生效。',
    'settings.security.passwordTooShort': '密码至少需要 6 位',
    'settings.security.passwordMismatch': '两次输入的密码不一致',
    'settings.security.invalidPassword': '当前密码不正确',
    'settings.security.operationFailed': '无法更新应用锁',
    'settings.security.enabledSuccess': '启动验证已开启',
    'settings.security.changedSuccess': '应用锁密码已更新',
    'settings.security.disabledSuccess': '启动验证已关闭',
    'settings.security.dangerZone': '危险区域',
    'settings.security.deleteAccount': '删除账号',
    'settings.security.deleteDescription': '永久删除您的账号及所有数据',
    'settings.security.deleteButton': '删除账号',

    // Settings - Notifications tab
    'settings.notifications.badge.controls': '通知控制',
    'settings.notifications.title': '减少噪音，不错过重要更新',
    'settings.notifications.description': '通知设置现已整合投递渠道、默认焦点和例外规则于一处。',
    'settings.notifications.section.delivery': '投递',
    'settings.notifications.section.deliveryDesc': '先决定哪些渠道可以联系到你。',
    'settings.notifications.channels.cardTitle': '投递渠道',
    'settings.notifications.channels.cardDesc': '选择告警到达方式。',
    'settings.notifications.channels.header': '通知渠道',
    'settings.notifications.channels.headerDesc': '配置通知接收方式',
    'settings.notifications.channels.email': '邮件',
    'settings.notifications.channels.emailDesc': '通过邮件接收更新',
    'settings.notifications.channels.dingtalk': '钉钉',
    'settings.notifications.channels.dingtalkDesc': '发送到钉钉 Webhook',
    'settings.notifications.channels.feishu': '飞书',
    'settings.notifications.channels.feishuDesc': '发送到飞书 Webhook',
    'settings.notifications.channels.wecom': '企业微信',
    'settings.notifications.channels.wecomDesc': '发送到企业微信 Webhook',
    'settings.notifications.channels.wechat': '微信',
    'settings.notifications.channels.wechatDesc': '通过微信机器人私聊接收通知',
    'settings.notifications.channels.inApp': '站内通知',
    'settings.notifications.channels.inAppDesc': '接收站内通知',
    'settings.notifications.channels.webhookUrl': 'Webhook 地址',
    'settings.notifications.section.focus': '焦点',
    'settings.notifications.section.focusDesc': '然后决定哪些仓库活动应该默认通知你。',
    'settings.notifications.focus.cardTitle': '默认通知焦点',
    'settings.notifications.focus.cardDesc': '此区域下一步将托管默认级别选择器。',
    'settings.notifications.focus.header': '通知焦点',
    'settings.notifications.focus.headerDesc': '这些开关是当前的基础设置，下一步将加入默认级别和基于规则的过滤。',
    'settings.notifications.events.highRisk': '高风险告警',
    'settings.notifications.events.highRiskDesc': '关键安全和性能问题',
    'settings.notifications.events.prUpdates': 'PR 更新',
    'settings.notifications.events.prUpdatesDesc': 'PR 创建、更新或合并',
    'settings.notifications.events.analysisComplete': '分析完成',
    'settings.notifications.events.analysisCompleteDesc': 'AI 分析完成',
    'settings.notifications.events.weeklyReport': '周报',
    'settings.notifications.events.weeklyReportDesc': '每周代码质量摘要',
    'settings.notifications.section.exceptions': '例外',
    'settings.notifications.section.exceptionsDesc': '快捷模板和例外规则，帮你精细控制通知噪音。',
    'settings.notifications.exceptions.cardTitle': '例外规则',
    'settings.notifications.exceptions.cardDesc': '焦点选择器之后，模板和高级过滤器将在此处呈现。',
    'settings.notifications.exceptions.incoming': '通知过滤功能即将迁移至此',
    'settings.notifications.exceptions.incomingDesc': '接下来我们会将默认焦点级别、快捷模板和例外规则直接整合到此标签页。',
    'settings.notifications.exceptions.planned': '计划中的模块',
    'settings.notifications.exceptions.plannedDesc': '默认通知级别、模板快捷方式、可读例外规则和高级预览。',
    'settings.notifications.save': '保存通知设置',
    'settings.notifications.saving': '保存中...',
    'settings.notifications.saved': '已保存！',

    // Settings - AI tab
    'settings.ai.title': 'AI 提供商配置',
    'settings.ai.description': '配置 AI 提供商以进行代码分析',
    'settings.ai.provider': 'AI 提供商',
    'settings.ai.providerPlaceholder': '选择 AI 提供商',
    'settings.ai.apiKey': 'API 密钥',
    'settings.ai.apiKeyPlaceholder': '输入 API 密钥',
    'settings.ai.apiKeyHint': '留空以保留现有 API 密钥',
    'settings.ai.baseUrl': '基础 URL',
    'settings.ai.baseUrlPlaceholder': 'https://api.example.com/v1',
    'settings.ai.endpointPreview': '端点预览',
    'settings.ai.testConnection': '测试连接',
    'settings.ai.testing': '测试中...',
    'settings.ai.model': '模型',
    'settings.ai.modelPlaceholder': '输入模型名称',
    'settings.ai.fetchModels': '获取模型列表',
    'settings.ai.fetching': '获取中...',
    'settings.ai.availableModels': '可用模型',
    'settings.ai.use': '使用',
    'settings.ai.save': '保存 AI 配置',
    'settings.ai.saving': '保存中...',
    'settings.ai.saved': '已保存！',


  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.keys(params).forEach(function (k) {
        text = text.replace('{' + k + '}', params[k]);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
