-- AlterTable: Add extended AI analysis fields
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "summaryShort" TEXT;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "summaryLong" TEXT;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "riskScore" INTEGER;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "riskReasons" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "affectedAreas" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "impactSummary" TEXT;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "suggestedAction" TEXT;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "confidence" DOUBLE PRECISION;
ALTER TABLE "AIAnalysis" ADD COLUMN IF NOT EXISTS "promptVersion" TEXT;
